### PR TITLE
fix: ignore non-exported decls in codegen

### LINKED ISSUE #1376: Update external module code generator to not generate decls based on visibility

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1376

### CODE REVIEW

**Review by worstell — APPROVED** [review]

File: integration/actions_test.go [hunk 1]
```diff
@@ -82,6 +82,32 @@ func exec(cmd string, args ...string) action {
 	}
 }
 
+// execWithOutput runs a command from the test working directory
```
Comment (alecthomas) [inline integration/actions_test.go:85]: This should mention that the output is returned as part of the error

**Comment by alecthomas** [comment]
This is awesome

**Review by alecthomas — APPROVED** [review]
