### PR TITLE
fix: use path from where vscode was launched

### LINKED ISSUE #1621: VSCode extension fails to run FTL in ftl-examples repo
image

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1621

This seems to better identify which ftl to use based on what `which ftl` returns for a given workspace.

> [!NOTE]  
> The path will not be detected correctly if a workspace is changed via File->Open...

### CODE REVIEW

File: extensions/vscode/src/extension.ts [hunk 1]
```diff
@@ -145,11 +144,13 @@ async function startClient(context: ExtensionContext) {
   console.log("Starting client")
 
   const ftlConfig = vscode.workspace.getConfiguration("ftl")
-  const ftlPath = ftlConfig.get<string>("executablePath") ?? "ftl"
+
   const workspaceRootPath = await getProjectOrWorkspaceRoot()
-  const ftlAbsolutePath = path.isAbsolute(ftlPath) ? ftlPath : path.resolve(workspaceRootPath, ftlPath)
+  const resolvedFtlPath = resolveFtlPath(workspaceRootPath, ftlConfig)
+
+  console.log('ftl path', resolvedFtlPath)
```
Comment (deniseli) [inline extensions/vscode/src/extension.ts:151]: did you want to remove this, or do we actually use console logs in prod?

File: extensions/vscode/src/config.ts [hunk 2]
```diff
@@ -45,6 +45,22 @@ export const findFileInWorkspace = async (rootPath: string, fileName: string): P
   return null
 }
 
+export const resolveFtlPath = (workspaceRoot: string, config: vscode.WorkspaceConfiguration): string => {
+  const ftlPath = config.get<string>("executablePath")
+  if (!ftlPath || ftlPath.trim() === '') {
+    try {
+      // Use `which` for Unix-based systems, `where` for Windows
```
Comment (deniseli) [inline extensions/vscode/src/config.ts:52]: niiiiiiice!

**Review by deniseli — APPROVED** [review]

File: extensions/vscode/src/extension.ts (hunk 1 above)
Comment (wesbillman) [reply extensions/vscode/src/extension.ts:151]: Yeah it's for debugging, but it actually only really shows in the debug log so I'll keep it for now! Thanks for catching it though! :)

File: extensions/vscode/src/config.ts [hunk 3]
```diff
@@ -45,6 +45,22 @@ export const findFileInWorkspace = async (rootPath: string, fileName: string): P
...
+      const command = process.platform === 'win32' ? 'where ftl' : 'which ftl'
```
[the remark this answers is not in the document]
Comment (alecthomas) [reply extensions/vscode/src/config.ts:53]: https://www.npmjs.com/package/lookpath
