### PR TITLE
fix: fail build when schema includes external types

### LINKED ISSUE #1066: Go schema extraction doesn't correctly validate data types are in FTL modules
The following code passes schema extraction when it shouldn't, because the type parameter of `ftl.Secret[did.PortableDID]("DID")` is not an FTL type.

```go

import (
  "github.com/tbd54566975/web5-go/dids/did"

  "github.com/TBD54566975/ftl/go-runtime/ftl"
)

var hostname = ftl.Config[string]("ENDPOINT")
var portableDID = ftl.Secret[did.PortableDID]("DID")
```

### PR DESCRIPTION
**Pull request by matt2e**
Fixes #1066

Building a module now fails if an external type is included in the schema.

Examples:
- `time.Month`
- `github.com/tbd54566975/web5-go/dids/did. PortableDID`

### CODE REVIEW

File: go-runtime/compile/schema.go [hunk 1]
```diff
@@ -667,6 +667,9 @@ func visitType(pctx *parseContext, node ast.Node, tnode types.Type) (schema.Type
 			} else if !strings.HasPrefix(nodePath, pctx.pkg.PkgPath) {
 				// If this type is named and declared in another module, it's a reference.
 				// The only basic-typed references supported are enums.
+				if !strings.HasPrefix(named.Obj().Pkg().Path(), "ftl/") {
```
Comment (alecthomas) [inline go-runtime/compile/schema.go:670]: This isn't going to interfere with the types in `go-runtime/ftl` like `ftl.Option` is it?

Comment (matt2e) [reply go-runtime/compile/schema.go:670]: Just gave it a try and it seemed to work
```
type EchoResponse struct {
	Message         string                    `json:"message"`
	OptionalString ftl.Option[string]        `json:"optionalString"` // This works fine
	OptionalDID     ftl.Option[did.BearerDID] `json:"optionalDID"` // This fails when included
}
```

**Comment by matt2e** [comment]
Looking into the test failures

**Comment by worstell** [comment]
these changes lgtm, but i think it may make sense to handle in `validate.go` rather than during schema extraction. we'd check that all `Ref` types in the schema can be resolved and fail if there are unresolvable references 

if we do decide to perform this check during extraction, we'll also need to add the equivalent in the kotlin schema extraction logic

**Comment by alecthomas** [comment]
@worstell it's already handled in validate, but it's a lot slower feedback cycle because it has to wait for a deploy...but that said, I'm not sure why we're not just calling Validate() after the build as that would give the same feedback...🤔

**Comment by matt2e** [comment]
An update before I clock off for the week. I went down the path of doing this in `validate.go` like you suggest @worstell, but got stuck since I couldnt get a path for a module (like ftl/example vs random/example), so it looks like I'm back to doing this in golang and kotlin.

File: buildengine/build_kotlin_test.go [hunk 2]
```diff
@@ -383,3 +387,20 @@ fun nothing(context: Context): Unit = throw
...
+	buildDir := "_ftl"
+
+	ctx := log.ContextWithLogger(context.Background(), log.Configure(os.Stderr, log.Config{}))
+	module, err := LoadModule(ctx, moduleDir)
+	assert.NoError(t, err)
+
+	sch := &schema.Schema{}
+	err = Build(ctx, sch, module)
+	//Expects: Expected module name to be in the form ftl.<module>, but was com.google.type.DayOfWeek"
+	assert.Error(t, err)
```
Comment (matt2e) [inline buildengine/build_kotlin_test.go:402]: I wanted to assert that the error contains the expected error string, but couldn't figure out how.
`err` doesn't seem to have any real info about the error, but the logger did print out the error.

Comment (alecthomas) [reply buildengine/build_kotlin_test.go:402]: `assert.EqualError()` is what you want

Comment (matt2e) [reply buildengine/build_kotlin_test.go:402]: The actual error string is not included in the error though. It is logged out rather than passed out through the error

Comment (alecthomas) [reply buildengine/build_kotlin_test.go:402]: Ah, that wasn't clear. For that your best bet is to add a Logger that writes to a `bytes.Buffer` to the context.

**Review by alecthomas — APPROVED** [review]
