### PR TITLE
fix: validate deploying module rather than entire schema

### LINKED ISSUE #1211: buildengine can reach a deadend where build errors can't be easily fixed by user
Steps to repro:
- start `ftl dev` with 2 modules, lets call them moduleA and moduleB
- in moduleA, create a verb and call it `VerbA`
- in moduleB, make a call to to the verb `moduleA.VerbA`
    - ftl autodetects the change and deploys both modules
- update moduleB to call modulaA.VerbB (even though it doesnt exist)
    - ftl autodetects the change and tries to build moduleB but fails. This is expected
- update moduleA's verb to be called VerbB instead of VerbA
    - ftl autodetects the change and tries to build moduleA and succeeds.
    - ftl then tries to deploy moduleA and fails:
 > error:controller0: Invalid module schema: invalid schema: .../moduleB/moduleB.go:29:16-16: unknown reference "moduleA.verbA"

The user can't really do much to untie this knot. Editing moduleB in small ways keeps failing with unknown reference for verbB. updating modulaA fails because a deployed module refers to verbA
- terminating ftl dev and rerunning it fixes the issue

### PR DESCRIPTION
**Pull request by worstell**
when deploying a module, we will only validate the deploying module's schema (but do so within the context of the greater schema).

this change prevents issues where a schema error outside of the deploying module prevents the deploy from succeeding—causing issues like #1211. now in combination with the buildengine logic, a change in the upstream module that breaks a downstream module will not prevent the upstream module from deploying (if the module still has a valid standalone schema). the deploy will succeed and then the subsequent deploy triggered for the downstream module will fail if the schema change from its dependency breaks it.

fixes #1211

### CODE REVIEW

**Review by wesbillman — APPROVED** [review]

File: backend/schema/validate.go [hunk 1]
```diff
@@ -38,15 +38,21 @@ var (
...
 	if err != nil {
 		panic(err)
 	}
 	return clone
 }
 
-// Validate clones, normalises and semantically valies a schema.
-func Validate(schema *Schema) (*Schema, error) {
+// ValidateWholeSchema clones, normalises and semantically validates a schema.
+func ValidateWholeSchema(schema *Schema) (*Schema, error) {
```
Comment (alecthomas) [inline backend/schema/validate.go:49]: ubernit: the "Whole" here seems redundant, but also isn't consistent with `ValidateModule()` - `schema.Validate()` is more idiomatic because it doesn't "stutter", but `schema.ValidateSchema()` could be preferable now because we now have a few different `Validate*()` functions

File: backend/schema/validate.go [hunk 2]
```diff
@@ -38,15 +38,21 @@ var (
...
+	return ValidateModuleInSchema(schema, nil)
+}
+
+// ValidateModuleInSchema clones and normalises a schema and semantically validates a single module within it.
+// If no module is provided, all modules in the schema are validated.
+func ValidateModuleInSchema(schema *Schema, m *Module) (*Schema, error) {
```
Comment (alecthomas) [inline backend/schema/validate.go:55]: I'm not 100% consistent with this myself, but I do try to use `Optional` in places where it conveys semantic meaning like it does here.

**Review by alecthomas — APPROVED** [review]
Great great catch, nice work.

**Comment by alecthomas** [comment]
I wonder if we should "un"deploy any broken modules so that the cluster isn't in an inconsistent state. This will be unnecessary in the future because we'll allow multiple versions to be active at once, and broken state will also be prevented on a "real" full deploy anyway, so probably not necessary

File: backend/schema/validate.go [hunk 3]
```diff
@@ -60,7 +66,7 @@ func Validate(schema *Schema) (*Schema, error) {
 
 	scopes := NewScopes()
 
-	// Validate dependencies
+	// ValidateWholeSchema dependencies
```
Comment (deniseli) [inline backend/schema/validate.go:69]: Should the change to this comment and the one on line 84 be undone? It looks like "Validate" was used as a regular English language verb in these two places, rather than being a reference to the `Validate` function

**Review by deniseli — APPROVED** [review]

File: backend/schema/validate.go (hunk 3 above)
Comment (worstell) [reply backend/schema/validate.go]: oop yes accidentally picked up from refactoring in my IDE! thanks for catching :)

File: backend/schema/validate.go (hunk 2 above)
Comment (worstell) [reply backend/schema/validate.go]: good to know, ty!
