### PR TITLE
fix: cron removed on module change

### LINKED ISSUE #3503: cronjobs fail to trigger if a module is redeployed/updated

### PR DESCRIPTION
**Pull request by stuartwdouglas**
fixes #3503

### CODE REVIEW

**Comment by alecthomas** [comment]
Can you describe the actual change here? Or preferably, add comments to the PR. The code doesn't make sense to me on the face of it, but that's probably because I don't understand the problem.

**Comment by stuartwdouglas** [comment]
I added some commends. Basically you need the 'added' message for the new deployment before you see the 'removed' message. The code the way it was would end up deleting a modules cron jobs when the old module was removed.

File: backend/cron/service.go [hunk 1]
```diff
@@ -78,6 +78,7 @@ func run(ctx context.Context, verbClient CallClient, changes chan *ftlv1.PullSch
 	logger := log.FromContext(ctx).Scope("cron")
 	// Map of cron jobs for each module.
 	cronJobs := map[string][]cronJob{}
+	currentDeploymentForModule := map[string]string{}
```
Comment (alecthomas) [inline backend/cron/service.go:81]: What I don't understand is that it looks like keys are never removed from this map?

Comment (stuartwdouglas) [reply backend/cron/service.go:81]: oops, that was an oversight, fixed. It would not have caused any actual issues in practice, unless you added and removed a huge number of modules.

File: backend/cron/service.go [hunk 2]
```diff
@@ -162,12 +165,23 @@ func scheduleNext(cronQueue []cronJob) (time.Duration, bool) {
 	return time.Until(cronQueue[0].next), true
 }
 
-func updateCronJobs(cronJobs map[string][]cronJob, resp *ftlv1.PullSchemaResponse) error {
+func updateCronJobs(ctx context.Context, cronJobs map[string][]cronJob, currentDeploymentsForModule map[string]string, resp *ftlv1.PullSchemaResponse) error {
+	logger := log.FromContext(ctx).Scope("cron")
 	switch resp.ChangeType {
 	case ftlv1.DeploymentChangeType_DEPLOYMENT_REMOVED:
+		// We see the new state of the module before we see the removed deployment.
```
Comment (alecthomas) [inline backend/cron/service.go:172]: Ah I see, that makes sense. Though if it's immediately ADDED, this shouldn't actually stop cron jobs from working as the ticket describes right?

**Review by alecthomas — CHANGES_REQUESTED** [review]
We should fix the underlying issue and reverse the order of the updates, rather than add hacks to work around it.

**Comment by stuartwdouglas** [comment]
The order of the updates is correct though, both deployments are running for a while for rolling deployments, and canaries will only make this worse.

File: backend/ingress/service.go [hunk 3]
```diff
@@ -100,13 +100,18 @@ func Start(ctx context.Context, config Config, pullSchemaClient PullSchemaClient
 					newState.protoSchema.Modules = append(newState.protoSchema.Modules, resp.Schema)
 				}
 			} else if existing != nil {
+				// We see the new state of the module before we see the removed deployment.
+				// We only want to actually remove if it was not replaced by a new deployment.
+				if !resp.ModuleRemoved {
```
Comment (alecthomas) [inline backend/ingress/service.go:105]: Yeah nice.

**Review by alecthomas — APPROVED** [review]
