### PR TITLE
fix: ftl new fails

### LINKED ISSUE #2297: `ftl new go ./foo bar` fails
```
🐚 ~/dev/ftl $ mkdir foo
🐚 ~/dev/ftl $ ftl new go ./foo bar
info: warning: could not open directory 'foo/foo/bar/': No such file or directory
fatal: pathspec 'foo/bar/*' did not match any files

ftl: error: exit status 128
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The directory was being prefixed to the path twice.

fixes #2297

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

File: cmd/ftl/cmd_new.go [hunk 1]
```diff
@@ -79,7 +79,7 @@ func (i newGoCmd) Run(ctx context.Context) error {
 				return err
 			}
 		}
-		if err := maybeGitAdd(ctx, i.Dir, filepath.Join(path, "*")); err != nil {
+		if err := maybeGitAdd(ctx, i.Dir, filepath.Join(i.Name, "*")); err != nil {
```
Comment (wesbillman) [inline cmd/ftl/cmd_new.go:82]: Thanks @stuartwdouglas!
