### PR TITLE
fix(console): when new module created|deleted updates/refreshes view

### LINKED ISSUE #163: When a new module is created the console view of that module does not get refreshed
Reproduction:

```
ftl initdb --recreate
ftl-dev
```

Open console in browser.

```
ftl go deploy -S $PWD -d ./examples/time
```

Go back to console and "time" should be visible. Click time and you will end up in an empty view.

### PR DESCRIPTION
**Pull request by EdwardIrby**
resolves #163

### CODE REVIEW

File: console/client/src/providers/modules-provider.tsx [hunk 1]
```diff
@@ -18,7 +20,7 @@ const ModulesProvider = (props: PropsWithChildren) => {
       return
     }
     fetchModules()
-  }, [client])
+  }, [client, schema])
```
Comment (wesbillman) [inline console/client/src/providers/modules-provider.tsx:23]: Nice!

**Review by wesbillman — APPROVED** [review]
