### PR TITLE
fix: reporting call and ingress event errors

### LINKED ISSUE #3149: Console swallows invalid request errors
Sending a bad request in Console shows nothing on screen. e.g.
`echo.echo`:
```
{
  "name": 1
}
```

There's a 500 response to /xyz.block.ftl.v1.VerbService/Call that isn't being handled

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #3149

Also fixes:
- ingress request keys were not being added to the database
- ingress events not adding to the db because of request body reading twice resulting in `error:timeline: Failed to insert 1 events, most recent error: failed to read request body: http: invalid Read on closed Body`
- call event errors were not being inserted as events (just logged)
- call not reusing the ingress request key correctly
- TimelineIcon not respecting error fields in responses

Screenshot 2024-10-18 at 9 55 13 AM
Screenshot 2024-10-18 at 9 55 35 AM

### CODE REVIEW

File: backend/controller/controller.go [hunk 1]
```diff
@@ -1074,6 +1072,34 @@ func (s *Service) callWithRequest(
...
+		ParentRequestKey: parentKey,
+		StartTime:        start,
+		DestVerb:         verbRef,
+		Callers:          callers,
+		Request:          req.Msg,
+	}
+
+	if currentCaller != nil && currentCaller.Module != module && !verb.IsExported() {
+		observability.Calls.Request(ctx, req.Msg.Verb, start, optional.Some("invalid request: verb not exported"))
+		err = connect.NewError(connect.CodePermissionDenied, fmt.Errorf("verb %q is not exported", verbRef))
```
Comment (deniseli) [inline backend/controller/controller.go:1087]: Since this is the same as the error you return, should this just be:
```
err = connect.NewError(connect.CodePermissionDenied, fmt.Errorf("verb %q is not exported", verbRef))
callEvent.Response = either.RightOf[*ftlv1.CallResponse](err)
s.timeline.EnqueueEvent(ctx, callEvent)
return nil, err
```

File: frontend/console/src/features/timeline/timeline.utils.ts [hunk 2]
```diff
@@ -22,4 +27,19 @@ const eventTextColorMap: Record<string, string> = {
...
+  return eventTextColorMap[event.entry.case || '']
+}
+
+const isError = (event: Event) => {
+  if (event.entry.case === 'call' && event.entry.value.error) {
+    return true
+  }
+  if (event.entry.case === 'ingress' && event.entry.value.error) {
+    return true
+  }
```
Comment (deniseli) [inline frontend/console/src/features/timeline/timeline.utils.ts:43]: `if (event.entry.value.error && ['call', 'ingress'].includes(event.entry.case))`? Or is there some nullability handling this doesn't work for hehe

**Review by deniseli — APPROVED** [review]
Niiiice

File: frontend/console/src/features/timeline/timeline.utils.ts (hunk 2 above)
Comment (wesbillman) [reply frontend/console/src/features/timeline/timeline.utils.ts:43]: Yeah it's the typical "make sure this is a call, then you can read the value.error" stuff :)

File: backend/controller/controller.go (hunk 1 above)
Comment (wesbillman) [reply backend/controller/controller.go:1087]: Nice, yeah good call. Updated.
