### PR TITLE
fix: ftltest config: use ConfigPaths with envar fallback

### LINKED ISSUE #1502: Allow module tests to be run from VS Code
We are close to having module unit tests work within VS Code. This will also make it easy to debug module code/tests.
The only thing missing is that `ftltest.WithProjectFiles()` relies on `FTL_CONFIG` envar.

Workarounds:
- Set the variable in hermit, open vscode with `code .`
- Set it up as an envar in VS Code's settings json
Both of these are annoying because you have to make sure you don't commit the changes because the path includes your home directory.

Possible solution:
We switch logic to look for expected file names in the current folder, if missing go up a level ... repeat.
This is similar to how you can call `just` from anywhere within the directory structure
We could make FTL_CONFIG and ftltest.WithProjectFiles(...) do this. This would make passing in strings to the test function actually usable in more cases, and the ftl config value to be able to be commited to git

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1502.

Adds tests to ensure we're correctly falling back to the config in `FTL_CONFIG` and to `ftl-project.toml` in the gitroot.

### CODE REVIEW

File: go-runtime/ftl/ftltest/ftltest.go [hunk 1]
```diff
@@ -73,10 +74,11 @@ func WithProjectFiles(paths ...string) Option {
 	var preprocessingErr error
 	if len(paths) == 0 {
 		envValue, ok := os.LookupEnv("FTL_CONFIG")
-		if !ok {
-			preprocessingErr = fmt.Errorf("loading project files: no path provided and FTL_CONFIG environment variable not set")
+		if ok {
+			paths = strings.Split(envValue, ",")
+		} else {
+			paths = pc.ConfigPaths(paths)
```
Comment (deniseli) [inline go-runtime/ftl/ftltest/ftltest.go:80]: Should we confirm that `paths` isn't [empty](https://github.com/TBD54566975/ftl/blob/main/common/projectconfig/projectconfig.go#L50) and return the same `preprocessingErr` error from before?

**Review by deniseli — APPROVED** [review]
nice!!

File: go-runtime/ftl/ftltest/ftltest.go (hunk 1 above)
Comment (safeer) [reply go-runtime/ftl/ftltest/ftltest.go:80]: My intention here is to have the [same behavior](https://github.com/TBD54566975/ftl/blob/cb3b3703ae24052f51794f3c7d5aa908406f9c86/common/projectconfig/merge.go#L15) as `main.go`, which allows `LoadConfig` to return an empty config after attempting to fall back on the envar, then the gitroot. I think having that parity makes sense?

Comment (deniseli) [reply go-runtime/ftl/ftltest/ftltest.go:80]: Ah, I see. I was wondering because I can't think of a reason why someone would use `WithProjectFiles` without any paths. From that perspective, I'd find it useful to get the error message during development so that I know the way I'm using `WithProjectFiles` isn't actually doing anything. `main.go` wouldn't want to error in that case because the project toml isn't required, whereas if someone is explicitly invoking `WithProjectFiles`, I'd assume they have some intent to actually use a project toml.

Comment (alecthomas) [reply go-runtime/ftl/ftltest/ftltest.go:80]: I think it's clear that if you're not passing explicit config files to `WithProjectFiles()` that whatever its described behaviour is is in effect. The `ftl-project.toml` file is designed to be the "default" for a project, and having it consistent across the CLI and tests is fine.

**Review by alecthomas — APPROVED** [review]
