### PR TITLE
fix: skip validation on external req/resp types

### LINKED ISSUE #1298: Three bugs that I don't know how to reproduce or fix
@michaelneale cloned down the ftl-examples and was unable to build the online-boutique for reasons that are not clear. I fixed a bunch of issues, but hit two weird bugs that are reproducible in [this branch](https://github.com/TBD54566975/ftl-examples/pull/30).

Bugs are:

1. We get the message `warn: "checkout" build skipped because its dependency "shipping" failed to build` even though shipping hasn't failed in any visible way.
2. We get `error: initial deploy failed: 14:3-3: ingress verb getQuote: couldn't resolve response body type currency.Money`
3. There's also a meta bug in that "initial deploy failed" doesn't tell me which file the failure is occurring in.

```
🐚 ~/dev/ftl-examples $ ftl dev online-boutique/backend --recreate
info: Starting FTL with 1 controller(s)
info:currency: Building module
info:cart: Building module
info:ad: Building module
info:ad: Deploying module
info:currency: Deploying module
info:cart: Deploying module
info:payment: Building module
info:shipping: Building module
info:productcatalog: Building module
info:payment: Deploying module
warn: "checkout" build skipped because its dependency "shipping" failed to build
info:recommendation: Building module
info:productcatalog: Deploying module
info:recommendation: Deploying module
info:controller0: Deployed dpl-ad-1m5ckbhogm6feil5
info:controller0: Deployed dpl-currency-1flmrlirote5ta9r
info:controller0: Deployed dpl-recommendation-58ikzredh79ww5d6
info:controller0: Deployed dpl-payment-9n2robh5f3vfo4w
info:controller0: Deployed dpl-productcatalog-099pwzdrb9zvpkq
info:controller0: Deployed dpl-cart-23tfpvcga9c6l85r
info: Modules waiting to build: shipping, checkout
error: initial deploy failed: 14:3-3: ingress verb getQuote: couldn't resolve response body type currency.Money
```

### PR DESCRIPTION
**Pull request by wesbillman**
We don't have access to the full schema at this point, so we can't validate that external types exist

Fixes #1298

### CODE REVIEW

**Review by worstell — APPROVED** [review]

File: backend/schema/validate.go [hunk 1]
```diff
@@ -512,9 +512,16 @@ func validateIngressRequestOrResponse(scopes Scopes, n *Verb, reqOrResp string,
...
+	if ref, err := ParseRef(fieldType.String()); err == nil {
+		if ref.Module != "" && ref.Module != module.Name {
+			return // ignores references to other modules.
+		}
+	}
+
 	bodySym := scopes.ResolveType(fieldType)
 	if bodySym == nil {
-		merr = append(merr, errorf(resp, "ingress verb %s: couldn't resolve %s body type %s", n.Name, reqOrResp, fieldType))
+		merr = append(merr, errorf(r, "ingress verb %s: couldn't resolve %s body type %s", n.Name, reqOrResp, fieldType))
```
Comment (wesbillman) [inline backend/schema/validate.go:524]: This fixes the issue where `initial deploy failed: 14:3-3: ingress verb getQuote:` is returned as an error. This was because of a typo that used `resp` instead of `r` for the `errorf(` call

File: backend/schema/validate.go [hunk 2]
```diff
@@ -512,9 +512,16 @@ func validateIngressRequestOrResponse(scopes Scopes, n *Verb, reqOrResp string,
 	if opt, ok := fieldType.(*Optional); ok {
 		fieldType = opt.Type
 	}
+
+	if ref, err := ParseRef(fieldType.String()); err == nil {
+		if ref.Module != "" && ref.Module != module.Name {
+			return // ignores references to other modules.
+		}
+	}
```
Comment (wesbillman) [inline backend/schema/validate.go:520]: This introduces logic to not validate resp body types for external modules since we don't have the full schema here, just a single module. This follows the comments for `ValidateModule` 
```go
// ValidateModule performs the subset of semantic validation possible on a single module.
//
// It ignores references to other modules.
func ValidateModule(module *Module) error {
```

Comment (alecthomas) [reply backend/schema/validate.go:520]: Does this get validated in `ValidateSchema` instead now? I don't see that in this PR.

Comment (wesbillman) [reply backend/schema/validate.go:520]: Yeah I believe that code is here: https://github.com/TBD54566975/ftl/blob/main/backend/schema/validate.go#L137 and tested here: https://github.com/TBD54566975/ftl/blob/main/backend/schema/schema_test.go#L211-L214
