### PR TITLE
Fix ordering of calls for the request graph

### LINKED ISSUE #274: Call graph is incorrectly picking "root" call under some circumstances
Image

It might be that we need to use IDs in the call events after all, or add span IDs.

### LINKED ISSUE #276: Call graph is reversed
I noticed that calls are reversed. That is, the top inner call represented in the graph is actually the last call issued by the ingress function.

Image

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #276 
Fixes #274 
Screenshot 2023-08-23 at 11 37 06 AM
Screenshot 2023-08-23 at 11 37 10 AM

### CODE REVIEW

File: backend/controller/internal/dal/events.go [hunk 1]
```diff
@@ -212,6 +212,8 @@ func (d *DAL) QueryEvents(ctx context.Context, after, before time.Time, filters
 		q += ")\n"
 	}
 
+	q += " ORDER BY time_stamp ASC"
```
Comment (wesbillman) [inline backend/controller/internal/dal/events.go:215]: @alecthomas 🤣🤣🤣🤣🤣🤣

Comment (alecthomas) [reply backend/controller/internal/dal/events.go:215]: WTF!
