### PR TITLE
fix: AdminService, config & secret CLI refactor, `--op=VAULT` deprecated

### LINKED ISSUE #1473: Refactor how config/secrets are managed so that all operations go through the controller
Currently the controller and CLI both operate directly on `ftl-project.toml`, as there was previously no mechanism for propagating config down to modules.  But now that we have `ModuleContext` we should change this. We'll need to for the production launch to support AWS anyway, but also because it's quite annoying.

This will entail adding new gRPC endpoints for secrets/config. Another consideration is that currently the CLI allows users to select a different provider (eg. 1Password, Keychain, etc.) per secret. To preserve this behaviour the desired provider will need to be passed to the Controller. However, the valid set of providers will vary depending on the target environment, so the Controller may error if an invalid provider is specified. eg. only ASM will be valid in production, so setting `--keychain` must error.

We want to start separating out "backend traffic" from "admin traffic", so to that end this new endpoint should be part of a new `AdminService` gRPC service rather than being part of the `ControllerService`.

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1473 by providing an `AdminService` and refactoring `cmd_config.go` and `cmd_secret.go` to use that service. The following CLI changes are included that may break existing clients:
- `ftl config` and `ftl secret` now require a running controller
- `ftl secret set <ref> --op=VAULT` is no longer supported
- `ftl-controller` and `ftl dev` accept a 1Password vault using `--opvault=VAULT`
- `ftl secret set <ref> --op` is supported, where `op` is a bool flag that requires the controller to have an `--opvault`

### CODE REVIEW

File: backend/controller/admin.go [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+	var value any
+	err := cm.Get(ctx, cf.NewRef(*req.Msg.Ref.Module, req.Msg.Ref.Name), &value)
+	if err != nil {
+		return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("failed to get value: %w", err))
+	}
+
+	buf := new(bytes.Buffer)
+	enc := json.NewEncoder(buf)
+	enc.SetIndent("", "  ")
+	err = enc.Encode(value)
```
Comment (alecthomas) [inline backend/controller/admin.go:80]: I think you can replace all this with `json.MarshalIndent()`

File: backend/controller/admin.go [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+	}
+
+	// TODO save the updated config
+
+	return connect.NewResponse(&ftlv1.SetConfigResponse{}), nil
+}
+
+// Unset a config value.
+func (s *AdminService) UnsetConfig(ctx context.Context, req *connect.Request[ftlv1.UnsetConfigRequest]) (*connect.Response[ftlv1.UnsetConfigResponse], error) {
+	cm := cf.ConfigFromContext(ctx) // TODO(saf): use cf.New to create a cm with the appropriate provider/writer
```
Comment (alecthomas) [inline backend/controller/admin.go:107]: Yeah I think it would be better to pass the config/secrets managers in as constructor arguments and have them as fields on the AdminService, rather than extracting them from the context over and over.

File: backend/protos/xyz/block/ftl/v1/ftl.proto [hunk 3]
```diff
@@ -375,3 +375,129 @@ service RunnerService {
...
+  ConfigRef ref = 2;
+}
+message GetConfigResponse {
+  string value = 1;
+}
+
+message SetConfigRequest {
+  optional ConfigProvider provider = 1;
+  ConfigRef ref = 2;
+  string value = 3;
```
Comment (alecthomas) [inline backend/protos/xyz/block/ftl/v1/ftl.proto:416]: Secret/config values are arbitrary JSON-encoded values, so this need to be `bytes`.

File: backend/controller/admin.go [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+}
+
+// Set a config value.
+func (s *AdminService) SetConfig(ctx context.Context, req *connect.Request[ftlv1.SetConfigRequest]) (*connect.Response[ftlv1.SetConfigResponse], error) {
+	cm := cf.ConfigFromContext(ctx) // TODO(saf): use cf.New to create a cm with the appropriate provider/writer
+	if err := cm.Mutable(); err != nil {
+		return nil, connect.NewError(connect.CodeInternal, err)
+	}
+
+	err := cm.Set(ctx, cf.NewRef(*req.Msg.Ref.Module, req.Msg.Ref.Name), req.Msg.Value)
```
Comment (alecthomas) [inline backend/controller/admin.go:95]: Mentioned elsewhere, but config/secret values are arbitrary JSON values, so this won't work as you'd expect.

We will also need to validate the values against their schema type before setting.

File: backend/protos/xyz/block/ftl/v1/ftl.proto [hunk 5]
```diff
@@ -375,3 +375,129 @@ service RunnerService {
...
+}
+message SetSecretResponse {}
+
+message UnsetSecretRequest {
+  optional SecretProvider provider = 1;
+  ConfigRef ref = 2;
+}
+message UnsetSecretResponse {}
+
+// AdminService centralizes project configuration access and provides CRUD operations.
```
Comment (alecthomas) [inline backend/protos/xyz/block/ftl/v1/ftl.proto:474]: I think generalise this comment.

File: backend/protos/xyz/block/ftl/v1/ftl.proto [hunk 6]
```diff
@@ -375,3 +375,129 @@ service RunnerService {
...
+service AdminService {
+  rpc Ping(PingRequest) returns (PingResponse) {
+    option idempotency_level = NO_SIDE_EFFECTS;
+  }
+
+  // List configuration.
+  rpc ListConfig(ListConfigRequest) returns (ListConfigResponse);
+
+  // Get a config value.
+  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse);
```
Comment (alecthomas) [inline backend/protos/xyz/block/ftl/v1/ftl.proto:484]: It reads a little weird, but I think it's preferable to start the method names with the type they're operating on: `ConfigGet`, `ConfigList`, etc. It makes completion and discovery much more obvious.

File: backend/controller/admin.go [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+	return connect.NewResponse(&ftlv1.GetConfigResponse{Value: vb}), nil
+}
+
+// ConfigSet sets the configuration at the given ref to the provided value.
+func (s *AdminService) ConfigSet(ctx context.Context, req *connect.Request[ftlv1.SetConfigRequest]) (*connect.Response[ftlv1.SetConfigResponse], error) {
+	var err error
+
+	// TODO(saf): use req.Msg.Provider to update / create a manager with the correct provider
+	cm := s.cm
+
```
Comment (safeer) [inline backend/controller/admin.go:93]: The `cm.Mutable()` call below fails because none of the providers are writeable. In its original state `cmd_config.go` would create a config manager with the specified writeable provider, but it seems problematic to do the same here.

**Review by gak — APPROVED** [review]
LGTM

File: backend/controller/controller.go [hunk 8]
```diff
@@ -130,6 +130,10 @@ func Start(ctx context.Context, config Config, runnerScaling scaling.RunnerScali
 	}
 	logger.Debugf("Listening on %s", config.Bind)
 
+	cm := cf.ConfigFromContext(ctx)
+	sm := cf.SecretsFromContext(ctx)
+
+	admin := NewAdminService(cm, sm)
```
Comment (wesbillman) [inline backend/controller/controller.go:136]: Nice!

**Review by wesbillman — APPROVED** [review]

**Comment by alecthomas** [comment]
Should this go in?

File: backend/controller/admin.go [hunk 9]
```diff
@@ -0,0 +1,199 @@
+package controller
+
```
[the remark this answers is not in the document]
Comment (safeer) [reply backend/controller/admin.go:2]: Addressing in a separate PR :)
