### PR TITLE
fix: only build verb schema for non-nil refs

### LINKED ISSUE #1578: ftl console fails to load deployments
ftl version: `0.226.0`

image

There should be 10 deployments. no build or deployment errors when running `ftl dev --recreate`.

inspecting browser console shows:

image

Looks like the following request is failing:
```
❯ curl -v \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'http://localhost:8892/xyz.block.ftl.v1.console.ConsoleService/GetModules' \
--data-raw '{}'
*   Trying [::1]:8892...
* connect to ::1 port 8892 failed: Connection refused
*   Trying 127.0.0.1:8892...
* Connected to localhost (127.0.0.1) port 8892
> POST /xyz.block.ftl.v1.console.ConsoleService/GetModules HTTP/1.1
> Host: localhost:8892
> User-Agent: curl/8.4.0
> Accept: application/json
> Content-Type: application/json
> Content-Length: 2
>
< HTTP/1.1 500 Internal Server Error
< Accept-Encoding: gzip
< Content-Type: application/json
< Date: Mon, 27 May 2024 22:40:10 GMT
< Content-Length: 53
<
* Connection #0 to host localhost left intact
{"code":"unknown","message":"failed to resolve Body"}%
```

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1578 

We might want more protection around refs not being found, but I wasn't sure how to make this allow for `TypeParameters` and also keep that protection. This fix gets things working again, but we might want to revisit this as well.

### CODE REVIEW

File: backend/controller/console.go [hunk 1]
```diff
@@ -44,15 +44,14 @@ func visitNode(sch *schema.Schema, n schema.Node, verbString *string) error {
...
-			*verbString += decl.String() + "\n\n"
-			err := visitNode(sch, decl, verbString)
-			if err != nil {
-				return err
+			if decl, ok := sch.Resolve(n).Get(); ok {
+				*verbString += decl.String() + "\n\n"
+				err := visitNode(sch, decl, verbString)
+				if err != nil {
+					return err
+				}
```
Comment (wesbillman) [inline backend/controller/console.go:52]: @alecthomas this change sort of undoes the change that was made here: https://github.com/TBD54566975/ftl/commit/3c91886259a0f6fb88ebd81db6f85ecd9105e5ee#diff-cf10aad402fc38d803d69ee88de91fa8b7f27d33ea52e2dc67ebb6749dfe61afR47-R50 so I wanted to call it out. 

Maybe there's a better approach we can use here, but wanted to fix the broken console until then.

Comment (alecthomas) [reply backend/controller/console.go:52]: This looks identical to me, just reordered, or am I missing something?

Comment (wesbillman) [reply backend/controller/console.go:52]: yeah it's very similar. The difference is that this one doesn't error if the `decl` cannot be resolved, it just skips it. This was happening for `Body` in the `HttpRequest<Body>` data types. Since `Body` isn't a ref that it can find.

Comment (wesbillman) [reply backend/controller/console.go:52]: So instead of:
```go
return fmt.Errorf("failed to resolve %s", n)
```
it just moves on to the next `Ref`

Comment (alecthomas) [reply backend/controller/console.go:52]: Aaah I see, makes sense
