### PR TITLE
fix: add `--watch` to `ftl schema get`

### LINKED ISSUE #1626: Add a `--watch` flag to `ftl schema get`
That just dumps each module as it streams from the controller.

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1626

### CODE REVIEW

File: cmd/ftl/cmd_schema_get.go [hunk 1]
```diff
@@ -44,17 +45,23 @@ func (g *getSchemaCmd) Run(ctx context.Context, client ftlv1connect.ControllerSe
...
 		}
 		if !msg.More {
-			break
+			missingNames := maps.Keys(remainingNames)
+			slices.Sort(missingNames)
+			if len(missingNames) > 0 {
+				if g.Watch {
+					fmt.Printf("missing modules: %v\n", missingNames)
+				} else {
+					return fmt.Errorf("missing modules: %v", missingNames)
```
Comment (wesbillman) [inline cmd/ftl/cmd_schema_get.go:54]: We should probably print this as a comma separate list for missingNames

**Review by wesbillman — APPROVED** [review]
Nice! That was easy :)
