### PR TITLE
fix: asm leader failing to read and write lease metadata

### LINKED ISSUE #2343: ASM leader coordination failing due to "unexpected end of JSON input"
`could not proactively coordinate leader for /system/asm: could not get lease for /system/asm: could not unmarshal lease metadata: unexpected end of JSON input`

- the leases metadata was empty in production
- deleting the lease caused another one to be created, again without any metadata

### PR DESCRIPTION
**Pull request by matt2e**
fixes #2343

### CODE REVIEW

File: backend/controller/dal/lease.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func (d *DAL) AcquireLease(ctx context.Context, key leases.Key, ttl time.Duratio
 			return nil, nil, fmt.Errorf("failed to marshal lease metadata: %w", err)
 		}
 	}
-	idempotencyKey, err := d.db.NewLease(ctx, key, sqltypes.Duration(ttl), pqtype.NullRawMessage{RawMessage: metadataBytes})
```
Comment (alecthomas) [inline backend/controller/dal/lease.go:99]: I think this was my fault! Might be an idea to check for other locations where I did this  😬

**Review by alecthomas — APPROVED** [review]

File: backend/controller/dal/lease.go (hunk 1 above)
Comment (matt2e) [reply backend/controller/dal/lease.go:99]: Made another issue for that 👍

Comment (alecthomas) [reply backend/controller/dal/lease.go:99]: I just checked, looks like this was the only location.
