### PR TITLE
fix: add a build.lock file to gate the buildengine

### LINKED ISSUE #1636: Add locking such that no two build tasks can run at the same time
`ftl build`, `ftl dev`, etc.

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1636

### CODE REVIEW

File: cmd/ftl/cmd_dev.go [hunk 1]
```diff
@@ -78,6 +85,15 @@ func (d *devCmd) Run(ctx context.Context, projConfig projectconfig.Config) error
 		if err != nil {
 			return err
 		}
+
```
Comment (safeer) [inline cmd/ftl/cmd_dev.go:88]: I'm having trouble getting `engine.Close()` called here and below

File: buildengine/engine.go [hunk 2]
```diff
@@ -167,6 +184,26 @@ func (e *Engine) Close() error {
...
+	homeDir, err := os.UserHomeDir()
+	if err != nil {
+		return nil, err
+	}
+	lockFile := filepath.Join(homeDir, ".ftl", "build.lock")
+	if err := os.MkdirAll(filepath.Dir(lockFile), 0750); err != nil {
+		return nil, err
+	}
+	lock := flock.New(lockFile)
+	locked, err := lock.TryLock()
```
Comment (wesbillman) [inline buildengine/engine.go:197]: Ohhh `flock` is cool :)
