### PR TITLE
fix: reduce error logs for failure to increase replicas

### LINKED ISSUE #1030: Implement reserved free runner pool
Currently in development we're suppressing this error:

```
warn:controller0: Failed to increase deployment replicas: failed to claim runners for oidcauth-86ae51d623: no idle runners found matching labels {"languages":["go"]}: not found
```

Because it triggers every time a new deployment is created. This message should not be suppressed however, and should probably be logged at error level.

A solution to this is to implement the reserved free runner pool that was in the original design for the autoscaling. That is, the controller will guarantee that a minimum number of free runners are always available.

### PR DESCRIPTION
**Pull request by matt2e**
fixes #1030

- Log level for failure to increase replicas depends on how many repeated attempts (error when >= 5)
- Increase default idle runners to 3

### CODE REVIEW

File: backend/controller/controller.go [hunk 1]
```diff
@@ -815,6 +840,16 @@ func (s *Service) reconcileDeployments(ctx context.Context) (time.Duration, erro
 			})
 		}
 	}
+
+	// Clean up old failures, which can happen if a deployment was removed before successfully reconciling.
```
Comment (alecthomas) [inline backend/controller/controller.go:844]: ubernit: maybe move this comment up to the declaration of `oldFailures` so it's a bit more obvious up front

**Review by alecthomas — APPROVED** [review]
Nice, LGTM.
