### PR TITLE
fix: support source and sink func declarations

### LINKED ISSUE #1065: Support for source and sink function declarations
Currently every exported function must be a "verb", accepting a request and returning a response, but we need to support declaring sources and sinks (as per the [primitives](https://hackmd.io/@ftl/By2xxh2uT) doc) in order to implement PubSub, but also because sometimes you just don't care about the request or response.

That is, we want to be able to accept:

```
//ftl:verb
func Sink(ctx context.Context, req Request) error {}

//ftl:verb
func Source(ctx context.Context) (Response, error) {}
```

We could also support neither request nor response, but we don't need this for PubSub.

```
//ftl:verb
func Foo(ctx context.Context) error {}
```

(the same should apply in Kotlin)

The missing values can be represented in the schema as `Unit`, eg.

```
verb sink(Request) Unit
verb source(Unit) Response
```

We'll also need to add additional `ftl.CallSink()` and `ftl.CallSource()` helpers, and equivalent in Kotlin.

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1065 

SOLVED: Some things to figure out still:

These were solved by assuming anything without a req is a source, anything without a resp, is a sink, and anything without either is empty.

1. How to use `Handle` with these new definitions. Since the signature no longer matches the `Handle` func, what should we do here? The generated code here will fail:
    ```go
    func main() {
      verbConstructor := server.NewUserVerbServer("time",
        server.Handle(time.Time),
        server.Handle(time.Sink), // these both have build errors since they don't match the expected signature
        server.Handle(time.Source),
      )
      plugin.Start(context.Background(), "time", verbConstructor, ftlv1connect.VerbServiceName, ftlv1connect.NewVerbServiceHandler)
    }
    ```

2. How should we deal with the fact that the generated code doesn't match the original signature? This also leads to issues using things like `ftl.callSink` and `ftl.callSource` since the generated code doesn't match the signature.
    ```go
    // original

    //ftl:verb
    func Source(context.Context) (SourceResp, error) {
    	return SourceResp{}, nil
    }
    
    // generated

    //ftl:verb
    func Source(context.Context, ftl.Unit) (SourceResp, error) {
      panic("Verb stubs should not be called directly, instead use github.com/TBD54566975/ftl/runtime-go/ftl.Call()")
    }
    ```

### CODE REVIEW

**Review by alecthomas — COMMENTED** [review]
Nice! Good start, but you're right, the other two points need to be addressed. LMK what you come up with.

File: go-runtime/ftl/call.go [hunk 1]
```diff
@@ -44,21 +43,61 @@ func Call[Req, Resp any](ctx context.Context, verb Verb[Req, Resp], req Req) (re
...
+func SourceToRef[Resp any](source Source[Resp]) SourceRef {
+	ref := runtime.FuncForPC(reflect.ValueOf(source).Pointer()).Name()
+	return SourceRef(goRefToFTLRef(ref))
+}
+
+// EmptyToRef returns the FTL reference for an Empty.
+func EmptyToRef(empty Empty) VerbRef {
+	ref := runtime.FuncForPC(reflect.ValueOf(empty).Pointer()).Name()
+	return goRefToFTLRef(ref)
+}
```
Comment (wesbillman) [inline go-runtime/ftl/call.go:99]: This stuff might change once we use a generic `Ref` everywhere. But this is working for now

File: go-runtime/server/server.go [hunk 2]
```diff
@@ -94,6 +92,47 @@ func Handle[Req, Resp any](verb func(ctx context.Context, req Req) (Resp, error)
...
+// HandleSink creates a Handler from a Sink with no response.
+func HandleSink[Req any](sink func(ctx context.Context, req Req) error) Handler {
+	ref := ftl.SinkToRef(sink)
+
+	verb := func(ctx context.Context, req Req) (ftl.Unit, error) {
+		err := sink(ctx, req)
+		return ftl.Unit{}, err
+	}
+
+	return handler(ftl.VerbRef{Module: ref.Module, Name: ref.Name}, verb)
```
Comment (wesbillman) [inline go-runtime/server/server.go:109]: Not sure if this is the best approach here, but it works as intended.

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt [hunk 3]
```diff
@@ -214,44 +214,55 @@ class SchemaExtractor(
       }
 
       // Validate parameters
-      require(verb.valueParameters.size == 2) { "$verbSourcePos Verbs must have exactly two arguments, ${verb.name} did not" }
+      require(verb.valueParameters.size >= 1) { "$verbSourcePos Verbs must have at least one argument, ${verb.name} did not" }
+      require(verb.valueParameters.size <= 2) { "$verbSourcePos Verbs must have at most two arguments, ${verb.name} did not" }
```
Comment (wesbillman) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:218]: @worstell would be good to get your 👀 on some of this `kotlin` stuff if you have a moment.

File: go-runtime/ftl/call.go (hunk 1 above)
Comment (alecthomas) [reply go-runtime/ftl/call.go:99]: @worstell says she has a change for this in flight

Comment (wesbillman) [reply go-runtime/ftl/call.go:99]: Awesome I can work with her to get her change and mine merged and updated here.

File: kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt [hunk 4]
```diff
@@ -34,8 +34,19 @@ data class {{.Name|title}}
 {{- else if is "Verb" . }}
 {{.Comments|comment -}}@Verb
 @Ignore
+{{- if and (eq (type $ .Request) "Unit") (eq (type $ .Response) "Unit")}}
+fun {{.Name|lowerCamel}}(context: Context): Unit = throw
```
Comment (alecthomas) [inline kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt:38]: You could probably pull `fun {{.Name|lowerCamel}}(context: Context` out from the if/else bodies if you wanted to DRY this a bit more.

**Review by alecthomas — APPROVED** [review]
LGTM but it would be good to add an integration test for these two cases.

File: go-runtime/compile/build.go [hunk 5]
```diff
@@ -201,6 +211,9 @@ var scaffoldFuncs = scaffolder.FuncMap{
 		}
 		panic(fmt.Sprintf("unsupported value %T", v))
 	},
+	"isSink": func(v schema.Verb) string {
+		return "wes"
```
[the remark this answers is not in the document]
Comment (wesbillman) [reply go-runtime/compile/build.go:215]: LOLOL

File: kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt (hunk 4 above)
Comment (wesbillman) [reply kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt:38]: I'll noodle on this one a bit. It makes the template quite a bit tougher for me to read, but maybe I'm just weird :)

File: integration/integration_test.go [hunk 6]
```diff
@@ -213,6 +213,22 @@ func TestExternalCalls(t *testing.T) {
 		return tests
 	})
 }
+func TestPubSub(t *testing.T) {
+	runForRuntimes(t, func(modulesDir string, runtime string, rd runtimeData) []test {
+		return []test{
+			{name: fmt.Sprintf("PubSub%s", rd.testSuffix), assertions: assertions{
+				run("ftl", rd.initOpts...),
+				scaffoldTestData(runtime, "pubsub", rd.modulePath),
```
Comment (wesbillman) [inline integration/integration_test.go:221]: I added these under `pubsub` assuming they can be extended to support `pubsub` once it's ready for integration tests.

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt [hunk 7]
```diff
@@ -214,44 +214,55 @@ class SchemaExtractor(
...
-      require(reqParam.typeReference?.resolveType()
-        ?.let { it.toClassDescriptor().isData || it.isEmptyBuiltin() }
-        ?: false
-      ) {
-        "${verb.valueParameters.last().getLineAndColumn()} Second argument of ${verb.name} must be a data class or " +
-          "builtin.Empty"
+      if (verb.valueParameters.size == 2) {
+        val reqParam = verb.valueParameters.last()
+        require(reqParam.typeReference?.resolveType()
+          ?.let { it.toClassDescriptor().isData || it.isEmptyBuiltin() || it.isUnit() }
```
Comment (worstell) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:228]: do we want to allow kotlin.Unit as a request type? i thought we were going to infer this from omission with the new change

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt [hunk 8]
```diff
@@ -214,44 +214,55 @@ class SchemaExtractor(
...
 
       // Validate return type
-      val respClass = verb.createTypeBindingForReturnType(bindingContext)?.type
-        ?: throw IllegalStateException("$verbSourcePos Could not resolve ${verb.name} return type")
-      require(respClass.toClassDescriptor().isData || respClass.isEmptyBuiltin()) {
-        "${verbSourcePos}: return type of ${verb.name} must be a data class or builtin.Empty but is ${
-          respClass.fqNameOrNull()?.asString()
-        }"
+      verb.createTypeBindingForReturnType(bindingContext)?.type?.let {
+        require(it.toClassDescriptor().isData || it.isEmptyBuiltin() || it.isUnit()) {
```
Comment (worstell) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:238]: same as above, do we want to look for a null return type instead of a `kotlin.Unit` return type?

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt (hunk 7 above)
Comment (wesbillman) [reply kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:228]: Ahh good catch! I had this in before I added the size check above and forgot to remove! Thanks for pointing this one out!

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt (hunk 8 above)
Comment (wesbillman) [reply kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:238]: On this one, I think `kotlin` infers the return type of `Unit` if it's omitted.

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt [hunk 9]
```diff
@@ -214,44 +214,55 @@ class SchemaExtractor(
...
+
+    var requestRef = Type(unit = xyz.block.ftl.v1.schema.Unit())
+    if (verb.valueParameters.size > 1) {
+      val ref = verb.valueParameters.last()?.let {
+        val position = it.getLineAndColumn().toPosition()
+        return@let it.typeReference?.resolveType()?.toSchemaType(position)
+      }
+      ref?.let { requestRef = it }
+
     }
```
Comment (worstell) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:258]:
```suggestion
    val requestRef = verb.valueParameters.takeIf { it.size > 1 }?.last()?.let {
      val position = it.getLineAndColumn().toPosition()
      return@let it.typeReference?.resolveType()?.toSchemaType(position)
    } ?: Type(unit = xyz.block.ftl.v1.schema.Unit())
```
```

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt [hunk 10]
```diff
@@ -214,44 +214,55 @@ class SchemaExtractor(
...
-    requireNotNull(requestRef) { "$verbSourcePos Could not resolve request type for ${verb.name}" }
-    val returnRef = verb.createTypeBindingForReturnType(bindingContext)?.let {
+
+    var returnRef = Type(unit = xyz.block.ftl.v1.schema.Unit())
+    val ref = verb.createTypeBindingForReturnType(bindingContext)?.let {
       val position = it.psiElement.getLineAndColumn().toPosition()
       return@let it.type.toSchemaType(position)
     }
```
Comment (worstell) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:264]:
```suggestion
    val returnRef = verb.createTypeBindingForReturnType(bindingContext)?.let {
      val position = it.psiElement.getLineAndColumn().toPosition()
      return@let it.type.toSchemaType(position)
    } ?: Type(unit = xyz.block.ftl.v1.schema.Unit())
```

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt (hunk 3 above)
Comment (worstell) [reply kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt:218]: lgtm!

File: kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt (hunk 4 above)
Comment (alecthomas) [reply kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt:38]: I was wondering that too. Just leave it as-is if it's too gross.
