### PR TITLE
fix: don't attempt to create ftl-project.toml in fs root

### LINKED ISSUE #1770: `ftl init` fails with `error: read-only file system`
Error when attempting to initialize a FTL Go module:
```
ftl init go . mymodule --log-level=DEBUG
debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.AdminService/Ping
debug: Initializing FTL Go module mymodule in .
debug: Creating a new project config file at "/ftl-project.toml"
ftl: error: open /ftl-project.toml3523669785: read-only file system
```

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1770

### CODE REVIEW

File: cmd/ftl/cmd_init.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func (i initGoCmd) Run(ctx context.Context, parent *initCmd) error {
 	if err := updateGitIgnore(i.Dir); err != nil {
 		return err
 	}
-	if err := projectconfig.MaybeCreateDefault(ctx); err != nil {
+	if err := projectconfig.MaybeCreateDefault(ctx, i.Dir); err != nil {
```
Comment (wesbillman) [inline cmd/ftl/cmd_init.go:74]: I think we might want to create the project file in the gitRoot folder vs. where this command was run. I just tried this in the FTL repo and it added the project file to `examples/go` since that's where I ran the `ftl init....` command. But I would guess we would want the file to be created at the root of the ftl repo.

**Review by wesbillman — COMMENTED** [review]
Nice! Thanks for taking a stab at this one!

File: cmd/ftl/cmd_init.go (hunk 1 above)
Comment (safeer) [reply cmd/ftl/cmd_init.go:74]: I agree; think we want the search for `ftl-project.toml` to end at the gitroot instead of walking up the tree to the fs root, then it would create it there if it doesn't exist. Was planning on bringing this up during standup, but I'm also wondering about the general assumption that the project is in a git repo. My test project wasn't and FTL was very angry.

Comment (safeer) [reply cmd/ftl/cmd_init.go]: @wesbillman added an explicit check for a git repo during `init`

Comment (wesbillman) [reply cmd/ftl/cmd_init.go]: Nice. Thanks!

Maybe we should just list the assumptions and make sure the code does what we expect. So maybe the process is something like this in order (please feel free to make changes or add assumptions here)

1. Check for existing ftl-project.toml.
2. Create new ftl-project.toml at the gitRoot if gitRoot is found
3. Create new ftl-project at the location where the `ftl init` command was run

I don't suspect we would ever want to create this at the FS root.

Comment (wesbillman) [reply cmd/ftl/cmd_init.go]: Chatted with @safeer and he's going to put together an RFC for changing the CLI to have more obvious commands for creating ftl projects and modules.

**Review by wesbillman — APPROVED** [review]
