### PR TITLE
fix: skip out of date file changes

### LINKED ISSUE #1210: File updates in quick succession leads to unnecessary builds
Steps to repro:
- run `ftl dev` with some modules
- start editing the code for a module
- make a small change, save the file, and repeat a few times in quick succession

FTL will queue up all these builds for the same module. After the last save, ftl will have a few of these in the queue. FTL will then build this same module a few times with the same result each time, which is unnecessary.
Possibly, we could look at the existing build to see if it started after the current message, as that would indicate the file change had already been included in the current build.

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1210 

This required a bit of a refactor to use pointers for `Module` and `ExternalLibrary` here. Hopefully, that's ok.

Example of rapid changes getting skipped. Note that I logged skips in `Warnf` just to highlight for this screenshot. Real skip messages are logged at `Debugf`

Screenshot 2024-04-16 at 2 03 09 PM

### CODE REVIEW

File: buildengine/build.go [hunk 1]
```diff
@@ -18,18 +18,18 @@ import (
 
 // Build a project in the given directory given the schema and project config.
 // For a module, this will build the module. For an external library, this will build stubs for imported modules.
-func Build(ctx context.Context, sch *schema.Schema, project Project) error {
-	switch project := project.(type) {
-	case Module:
+func Build(ctx context.Context, sch *schema.Schema, proj Project) error {
+	switch project := proj.(type) {
```
Comment (alecthomas) [inline buildengine/build.go:22]: You can and should just do `switch project := project.(type) {`

File: buildengine/build.go [hunk 2]
```diff
@@ -18,18 +18,18 @@ import (
...
+	case *Module:
```
Comment (alecthomas) [inline buildengine/build.go:23]: Why the pointer change?

File: buildengine/engine.go [hunk 3]
```diff
@@ -285,12 +285,19 @@ func (e *Engine) watchForModuleChanges(ctx context.Context, period time.Duration
 				delete(e.projects, config.Key)
 			case WatchEventProjectChanged:
 				config := event.Project.Config()
+
+				lastBuildTime := e.projects[config.Key].GetLastBuildStartTime()
```
Comment (alecthomas) [inline buildengine/engine.go:289]: I think rather than making all these changes because of making Project mutable, just change the `e.projects` map to use an intermediate struct that contains the `Project` + `time.Time`:

```go
type projectMeta struct {
  project Project
  lastBuildStartTime time.Time
}
```

Comment (wesbillman) [reply buildengine/engine.go:289]: Love it! Thanks dude!

File: buildengine/engine.go [hunk 4]
```diff
@@ -32,6 +32,11 @@ type schemaChange struct {
 	*schema.Module
 }
 
+type projectMeta struct {
+	project            Project
+	lastBuildStartTime time.Time
+}
```
Comment (wesbillman) [inline buildengine/engine.go:38]: @alecthomas I moved away from embedding because it seems to cause more confusion than help. For example some of the methods that took in a `project Project` would be ok with a `projectMeta` but then the type assertions would require a `projectMeta` case and I was getting lots of bugs where I should be using `project.project` but I was just using `project` directly. lemme know if this seems reasonable :)

**Review by alecthomas — APPROVED** [review]
