### PR TITLE
fix: allow integration tests to run from anywhere

### LINKED ISSUE #1384: Allow the `integrationtest` framework to be used from anywhere
Currently all tests must be in the `integrationtest` directory, but it would be much nicer if we could run integration tests from anywhere in the source tree, such that the tests for a particular package live alongside that package.

This should be relatively straightforward:

1. Make the DSL an importable package rather than only visible to tests in the integrationtest package.
2. Resolve any assumptions about location in the source tree.
3. Update the GH workflow to find and run integration tests from anywhere.

### PR DESCRIPTION
**Pull request by jonathanj-square**
fixes #1384 

- exposes DSL steps as public for use in other packages
- modify the `integration test` just command to search for dirs containing the integration test tag

### CODE REVIEW

File: integration/actions_test.go [hunk 1]
```diff
@@ -29,9 +29,9 @@ import (
 	"github.com/TBD54566975/scaffolder"
 )
 
-// scaffold a directory relative to the testdata directory to a directory relative to the working directory.
-func scaffold(src, dest string, tmplCtx any) action {
-	return func(t testing.TB, ic testContext) error {
+// Scaffold a directory relative to the testdata directory to a directory relative to the working directory.
```
Comment (alecthomas) [inline integration/actions_test.go:32]: Can't see it here, but the package is currently named `simple_test`. The files will have to be renamed to drop `_test.go` (except `integration_test.go`), the public API will have to be renamed to `integration`.

The `integration_test.go` file should be in the package `integration_test`.

File: integration/harness_test.go [hunk 2]
```diff
@@ -42,8 +42,9 @@ var buildOnce sync.Once
 
 // run an integration test.
 // ftlConfigPath: if FTL_CONFIG should be set for this test, then pass in the relative
-//   path from integration/testdata/go/. e.g. "database/ftl-project.toml"
-func run(t *testing.T, ftlConfigPath string, actions ...action) {
+//
+//	path from integration/testdata/go/. e.g. "database/ftl-project.toml"
+func run(t *testing.T, ftlConfigPath string, actions ...Action) {
```
Comment (alecthomas) [inline integration/harness_test.go:47]: This will need to be public.

File: integration/harness_test.go [hunk 3]
```diff
@@ -42,8 +42,9 @@ var buildOnce sync.Once
 
 // run an integration test.
 // ftlConfigPath: if FTL_CONFIG should be set for this test, then pass in the relative
-//   path from integration/testdata/go/. e.g. "database/ftl-project.toml"
-func run(t *testing.T, ftlConfigPath string, actions ...action) {
+//
+//	path from integration/testdata/go/. e.g. "database/ftl-project.toml"
```
Comment (alecthomas) [inline integration/harness_test.go:46]: This comment should be changed such that the base directory is relative to where the test is

**Review by alecthomas — COMMENTED** [review]
Looking good but let's verify this works by moving the HTTP ingress test(s) to `backend/controller/ingress`.

**Comment by alecthomas** [comment]
You'll also need to update the integration test sharding in `.github/workflows/ci.yml`

File: Justfile [hunk 4]
```diff
@@ -114,7 +114,7 @@ integration-tests *test:
   #!/bin/bash
   set -euo pipefail
   testName=${1:-}
-  go test -fullpath -count 1 -v -tags integration -run "$testName" ./integration ./backend/controller/cronjobs
+  go test -fullpath -count 1 -v -tags integration -run "$testName" $(git grep -l --untracked '^//go:build integration' | xargs -I {} dirname './{}' | sort | uniq)
```
Comment (alecthomas) [inline Justfile:117]: You should be able to just use `./...` here and Go will figure it out.

Comment (jonathanj-square) [reply Justfile:117]: excellent, should the `integration-run` target in `.github/workflows/ci.yml` also replace this grep sequence with `./...`?

Comment (alecthomas) [reply Justfile]: Unfortunately not, in that location the shell fragment is trying to quickly figure out what the test shards are so it should use something like the above. However in this location that's not an issue as the tests aren't being sharded.

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -182,7 +182,7 @@ jobs:
       - name: Run ${{ matrix.test }}
         run: |
           # shellcheck disable=SC2046
-          go test -v -race -tags integration -run ${{ matrix.test }} $(git grep -l '^//go:build integration' | xargs -I {} dirname './{}' | sort | uniq)
+          go test -v -race -tags integration -run ${{ matrix.test }} ./...
```
Comment (alecthomas) [inline .github/workflows/ci.yml:185]: Yep, as mentioned in the other comment this one should stay.

Comment (alecthomas) [reply .github/workflows/ci.yml:185]: Line 159 is the one I was thinking of, but it actually looks like that's already doing the correct thing, so disregard!

File: integration/integration_test.go [hunk 6]
```diff
@@ -18,6 +18,7 @@ import (
 
 	ftlv1 "github.com/TBD54566975/ftl/backend/protos/xyz/block/ftl/v1"
 	schemapb "github.com/TBD54566975/ftl/backend/protos/xyz/block/ftl/v1/schema"
+	"github.com/TBD54566975/ftl/integration"
```
Comment (alecthomas) [inline integration/integration_test.go:21]: Ah I should have mentioned I think in cases like this it's fine to use a "dot" import eg.

```
. "github.com/TBD54566975/ftl/integration"
```

This brings all of the symbols from that package into the current namespace, meaning you don't have to prefix every symbol with the package name.

**Review by alecthomas — APPROVED** [review]
LGTM once the test fixtures are moved and the tests pass!

File: integration/integration_test.go (hunk 6 above)
Comment (wesbillman) [reply integration/integration_test.go:21]: oh neat! I didn't know about this either. Thanks!

File: backend/controller/ingress/testdata/go/httpingress/go.sum
Comment (alecthomas) [inline backend/controller/ingress/testdata/go/httpingress/go.sum:1]: You'll likely need to fix the `replace` directive in this file so that its relative path stays the same.
