### PR TITLE
fix: ps cmd should ignore dead runners

### LINKED ISSUE #1046: ps cmd can show inaccurate state
Sometimes old runners are shown for deployments.

Working on getting steps to repro

### PR DESCRIPTION
**Pull request by matt2e**
fixes #1046

Runners that were found to have died (rather than cleanly being killed) end up with deployment_id & module_name not set to null.
Changes:
- removes all dead runners from showing in the `ps` command
- correctly updates `deployment_id` and `module_name` to null in the following cases:
    -  Runner terminates unexpectedly
    -  Runner is stale

### CODE REVIEW

**Comment by alecthomas** [comment]
Are these runners getting reaped eventually, and if so does the reaping correctly set the module_name to NULL eventually? If not it seems like we should fix that?

File: backend/controller/sql/queries.sql [hunk 1]
```diff
@@ -160,7 +160,7 @@ SELECT d.min_replicas,
        r.endpoint,
        r.labels AS runner_labels
 FROM deployments d
-         LEFT JOIN runners r on d.id = r.deployment_id
+         LEFT JOIN runners r on d.id = r.deployment_id AND r.state = 'assigned'
```
Comment (alecthomas) [inline backend/controller/sql/queries.sql:163]: Hmmm actually if we just want to ignore dead runners, this probably isn't the right solution. We probably do want `!= 'dead'` so that it will also pick up runners that are reserved.

**Review by alecthomas — APPROVED** [review]

File: backend/controller/sql/queries.sql (hunk 1 above)
Comment (alecthomas) [reply backend/controller/sql/queries.sql:163]: I'm not 100% sure I'm right there, so it would be worth verifying if that does what we want...

Comment (matt2e) [reply backend/controller/sql/queries.sql:163]: Makes sense, will fix

**Comment by matt2e** [comment]
> Are these runners getting reaped eventually, and if so does the reaping correctly set the module_name to NULL eventually? If not it seems like we should fix that?
Looking into why it's not being set to null.
I don't think the reap job touches these runners because they are set to dead immediately, and the SQL for that filters by `<> dead`

**Comment by matt2e** [comment]
It's the deregister runner code that is setting it to dead in the db without updating `deployment_id` and `module_name`. I've updated the sql to amend that.

But I think the reap case will also end up those columns not nulled out... I'll set this PR back to draft and try recreating that case next week

**Comment by matt2e** [comment]
Handled the above cases and updated PR description

**Review by alecthomas — APPROVED** [review]
