### PR TITLE
fix: retryable streaming server errors to be logged as debug

### LINKED ISSUE #2002: `ftl build` warns repeatedly about connection refused
- No FTL was running when I started.
- `ftl build --log-level=DEBUG` in the `ftl` repo

### Logs
```
debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.AdminService/Ping
debug: Extracting dependencies for "echo"
debug: Extracting dependencies for "time"
debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/GetSchema
debug: Failed to get schema from controller: unavailable: dial tcp [::1]:8892: connect: connection refused
debug: Extracting dependencies for "echo"
warn: Stream handler failed, retrying in 100ms: unavailable: dial tcp [::1]:8892: connect: connection refused
debug: Extracting dependencies for "time"
debug: Generating stubs for modules
warn: Stream handler failed, retrying in 200ms: unavailable: dial tcp [::1]:8892: connect: connection refused
debug: go: finding module for package github.com/TBD54566975/ftl/go-runtime/ftl
debug: go: found github.com/TBD54566975/ftl/go-runtime/ftl in github.com/TBD54566975/ftl v0.281.0
info:time: Building module
debug:time: Extracting schema
warn: Stream handler failed, retrying in 400ms: unavailable: dial tcp [::1]:8892: connect: connection refused
warn: Stream handler failed, retrying in 800ms: unavailable: dial tcp [::1]:8892: connect: connection refused
debug:time: Generating main module
debug:time: Tidying go.mod files
debug:time: go: found github.com/TBD54566975/ftl/backend/protos/xyz/block/ftl/v1/ftlv1connect in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:time: go: found github.com/TBD54566975/ftl/common/plugin in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:time: go: found github.com/TBD54566975/ftl/go-runtime/server in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:time: Compiling
warn: Stream handler failed, retrying in 1s: unavailable: dial tcp [::1]:8892: connect: connection refused
info:time: Module built (2.22s)
debug: Generating stubs for modules
warn: Stream handler failed, retrying in 1s: unavailable: dial tcp [::1]:8892: connect: connection refused
debug: go: finding module for package github.com/TBD54566975/ftl/go-runtime/ftl
debug: go: found github.com/TBD54566975/ftl/go-runtime/ftl in github.com/TBD54566975/ftl v0.281.0
info:echo: Building module
debug:echo: Extracting schema
warn: Stream handler failed, retrying in 1s: unavailable: dial tcp [::1]:8892: connect: connection refused
debug:echo: Generating main module
debug:echo: Tidying go.mod files
warn: Stream handler failed, retrying in 1s: unavailable: dial tcp [::1]:8892: connect: connection refused
debug:echo: go: found github.com/TBD54566975/ftl/backend/protos/xyz/block/ftl/v1/ftlv1connect in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:echo: go: found github.com/TBD54566975/ftl/common/plugin in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:echo: go: found github.com/TBD54566975/ftl/go-runtime/server in github.com/TBD54566975/ftl v0.0.0-00010101000000-000000000000
debug:echo: Compiling
warn: Stream handler failed, retrying in 1s: unavailable: dial tcp [::1]:8892: connect: connection refused
info:echo: Module built (2.79s)
```

### PR DESCRIPTION
**Pull request by jonathanj-square**
fixes #2002

unexpected warnings caused by retryable errors - retryable errors will continue to be reported as debug.

### CODE REVIEW

File: internal/rpc/rpc.go [hunk 1]
```diff
@@ -240,7 +240,6 @@ func RetryStreamingServerStream[Req, Resp any](
 				} else {
 					// Stream terminated; check if this was caused by an error
 					err = stream.Err()
```
Comment (deniseli) [inline internal/rpc/rpc.go:242]: Should we check if the error type is actually a `connect: connection refused` error? I'm guessing there could be other error types here where we _do_ want `log.Warn`

File: internal/rpc/rpc.go [hunk 2]
```diff
@@ -240,7 +240,9 @@ func RetryStreamingServerStream[Req, Resp any](
...
-					logLevel = log.Warn
+					if !useDebugErrorLevel(err) {
```
Comment (deniseli) [inline internal/rpc/rpc.go:243]: For readability, could we refactor this to `logLevel = logLevelForError(err)`? That way, you don't need to mentally parse the `!` and the variable scope/flow.

**Review by deniseli — APPROVED** [review]

File: internal/rpc/rpc.go [hunk 3]
```diff
@@ -268,3 +268,12 @@ func RetryStreamingServerStream[Req, Resp any](
 
 	}
 }
+
+// useDebugErrorLevel indicates whether the specified error should be reported as a debug
```
Comment (deniseli) [inline internal/rpc/rpc.go:272]: nit: would you mind making a quick followup PR to fix this comment? Thanks! :)

File: internal/rpc/rpc.go [hunk 4]
```diff
@@ -268,3 +268,12 @@ func RetryStreamingServerStream[Req, Resp any](
...
+// level log.
+func logLevelForError(err error) log.Level {
+	if err != nil && strings.Contains(err.Error(), "connect: connection refused") {
```
Comment (deniseli) [inline internal/rpc/rpc.go:275]: It's better to use `errors.Is` for this check, like: https://go.dev/play/p/M0X4W1wcSQn

Sorry I missed this earlier!
