### PR TITLE
fix: remove old subscriptions and subscribers

### LINKED ISSUE #1660: Remove pubsub reliance on min_replicas
See comments here: https://github.com/TBD54566975/ftl/pull/1641#discussion_r1625613624

### LINKED ISSUE #1685: Pubsub can end up blocked by subscriptions with no subscribers
- Have 5 subscriptions with no subscribers
- Publish events to each subscription's topic
- <Time passes>
- Now when controllers try to progress subscriptions, they will always get these subscriptions because they have the oldest cursor and we limit by 3
- controllers try to progress 3 of these subscriptions, which becomes a no-op because there are no subscribers
- ... repeat indefinitely, so we never actually progress subscriptions with newer cursors and actual subscribers

### PR DESCRIPTION
**Pull request by matt2e**
fixes #1660
fixes #1685

changes:
- add hooks for when we activate and deactivate deployments (`min_replicas > 0` vs `min_replicas == 0`)
- when activating a deployment:
    - upsert subscriptions (maintain state), insert subscribers
    - skip subscriptions with no subscribers (ie: do not insert into db)
- when deactivating a deployment:
    - delete subscriptions still owned by deployment
    - delete subscribers

Skipping subscriptions without subscribers fixes the case where pubsub manager would get stuck trying to progress subscriptions without subscribers, blocking real subscriptions from progressing.

### CODE REVIEW

**Comment by alecthomas** [comment]
Off the top of my head, inserting new topics/subscriptions when creating the new deployment, and dropping all unused ones in the remove deployment seems reasonable. I don't know how painful that would be.

File: backend/controller/dal/dal.go [hunk 1]
```diff
@@ -501,22 +501,51 @@ func (d *DAL) CreateDeployment(ctx context.Context, language string, moduleSchem
...
+				return false
+			}
+			_, subscribes := slices.Find(v.Metadata, func(in schema.Metadata) bool {
+				md, ok := in.(*schema.MetadataSubscriber)
+				if !ok {
+					return false
+				}
+				return md.Name == s.Name
+			})
+			return subscribes
```
Comment (deniseli) [inline backend/controller/dal/dal.go:524]: really nitty nit pick on readability: If you pull this logic into a helper function `hasSubscriber`, you can do:

```
if hasSubscriber(moduleSchema.Decls) {
  // Ignore subscriptions without ...
  continue
}
```

This (1) shortens the for-loop so it's easier to read/comprehend and (2) communicates "look for subscribers" with a func name instead of a comment, which is slightly better for maintainability

File: backend/controller/sql/queries.sql [hunk 2]
```diff
@@ -645,6 +645,20 @@ UPDATE SET
   topic_id = excluded.topic_id
 RETURNING id;
 
+-- name: DeleteOldSubscriptions :exec
```
Comment (deniseli) [inline backend/controller/sql/queries.sql:648]: nitty nitty naming nit: should this be `DeleteUnusedSubscriptions` or `DeleteObsoleteSubscriptions` since the selection criteria is whether the subscription is used, not whether it's aged past a certain TTL (time to live) date?

File: backend/controller/dal/dal.go [hunk 3]
```diff
@@ -501,22 +501,51 @@ func (d *DAL) CreateDeployment(ctx context.Context, language string, moduleSchem
...
-		if err != nil {
+		}); err != nil {
 			return model.DeploymentKey{}, fmt.Errorf("could not insert subscription: %w", translatePGError(err))
 		}
+		subscriptionNames = append(subscriptionNames, s.Name)
+	}
+	if err := tx.DeleteOldSubscriptions(ctx, moduleSchema.Name, subscriptionNames); err != nil {
+		return model.DeploymentKey{}, fmt.Errorf("could not delete old subscriptions: %w", translatePGError(err))
+	}
+	if err := tx.DeleteSubscribers(ctx, moduleSchema.Name); err != nil {
```
Comment (deniseli) [inline backend/controller/dal/dal.go:547]: Re:
> These db updates are done in the db commit which inserts the deployment. At that time the previous deployment is still live and the new deployment has min_replicas set to 0. If the next commit (ReplaceDeployment) does not complete then the old deployment will be in a bad state (all subscribers stop receiving events).

Is it possible to refactor this code to combine the 2 commits into a single [Postgres Transaction](https://www.postgresql.org/docs/current/tutorial-transactions.html)? That basically turns it into a single atomic operation, so that if something goes wrong with the second step, then the first will not be committed either. I don't know this code very well, so that may well be a bad idea :p

**Review by deniseli — APPROVED** [review]

File: backend/controller/dal/dal.go (hunk 3 above)
Comment (matt2e) [reply backend/controller/dal/dal.go:547]: I think there's history in this area of code for why we create a deployment in one transaction, and then replace the old deployment with the new deployment in a second commit. I think @wesbillman mentioned when I first joined that this area had recently gone through some hardening to catch glitches?

File: backend/controller/sql/queries.sql (hunk 2 above)
Comment (matt2e) [reply backend/controller/sql/queries.sql:648]: That's better naming 👍

File: backend/controller/dal/dal.go (hunk 1 above)
Comment (matt2e) [reply backend/controller/dal/dal.go:524]: Yeh agreed, thanks Denise

**Comment by matt2e** [comment]
> Off the top of my head, inserting new topics/subscriptions when creating the new deployment, and dropping all unused ones in the remove deployment seems reasonable. I don't know how painful that would be.

ended up doing this 👍 It requires an extra column in `subscriptions` to point to the latest deployment it is part of

**Comment by matt2e** [comment]
@alecthomas ok that didn't exactly work. Here's the bad case steps:
- `ftl dev`
- Initial deploy, creates pubsub records
- change code, save
    - `CreateDeployment()` inserts the deployment, insert/update subscriptions/subscribers
    - ReplaceDeployment gets called, deletes old subscriptions/subscribers
- undo code changes, save
    - `CreateDeployment()` exits early because we detect that the original deployment matches what we need
        - we do not insert/update the subscriptions.subscribers
    - ReplaceDeployment gets called, deletes old subscriptions/subscribers
- So we end up with no subscriptions/subscribers for the module

So the solution has evolved a bit:
- Added hooks for `deploymentWillActivate` and `deploymentWillDeactivate` in `dal/dal.go`
    - called by `ReplaceDeployment` and `SetDeploymentReplicas`
- Moved all this pubsub specific code to `dal/pubsub.go`
- This also handles cases like modules being removed and then re-added (eg by changing branches)

File: backend/controller/sql/queries.sql (hunk 2 above)
Comment (matt2e) [reply backend/controller/sql/queries.sql]: (Renamed again because its changed whats it's doing)

File: backend/controller/dal/dal.go (hunk 3 above)
Comment (deniseli) [reply backend/controller/dal/dal.go]: Oh interesting...

**Review by alecthomas — APPROVED** [review]
