### PR TITLE
docs(lsp): more completions. fix bug with completions.

### LINKED ISSUE #1757: Add remaining hover and completions for ftl things in LSP
The work has started with `ftl:verb` and `ftl:enum`, but we should add the rest of the FTL supported hover information and completions.

### PR DESCRIPTION
**Pull request by gak**
Completions were sometimes not being triggering correctly.

Fixes #1757

### CODE REVIEW

File: lsp/completion.go [hunk 1]
```diff
@@ -18,24 +19,76 @@ var enumTypeCompletionDocs string
...
+// Markdown is split by "---". First half is completion docs, second half is insert text.
 var completionItems = []protocol.CompletionItem{
 	completionItem("ftl:verb", "FTL Verb", verbCompletionDocs),
 	completionItem("ftl:enum (sum type)", "FTL Enum (sum type)", enumTypeCompletionDocs),
 	completionItem("ftl:enum (value)", "FTL Enum (value type)", enumValueCompletionDocs),
+	completionItem("ftl:typealias", "FTL Type Alias", typeAliasCompletionDocs),
+	completionItem("ftl:ingress", "FTL Ingress", ingressCompletionDocs),
+	completionItem("ftl:cron", "FTL Cron", cronCompletionDocs),
+	completionItem("ftl:retry", "FTL Retry", retryCompletionDocs),
+	completionItem("config:declare", "Declare config", declareConfigCompletionDocs),
```
Comment (alecthomas) [inline lsp/completion.go:67]: Maybe these should have `ftl:` prefixes too?

**Comment by gak** [comment]
There's still FSM to do.

File: lsp/completion.go [hunk 2]
```diff
@@ -18,24 +19,76 @@ var enumTypeCompletionDocs string
...
-	// First half is completion docs, second half is insert text
 	parts := strings.Split(markdown, "---")
 	if len(parts) != 2 {
 		panic("invalid markdown. must contain exactly one '---' to separate completion docs from insert text")
 	}
 
 	insertText := strings.TrimSpace(parts[1])
+	// Warn if we see two spaces in the insert text.
+	if strings.Contains(insertText, "  ") {
+		fmt.Fprintf(os.Stderr, "warning: completion item %q contains two spaces in the insert text. Use tabs instead!\n", label)
```
Comment (alecthomas) [inline lsp/completion.go:89]: Are we using fmt.Fprintf for debug logging? I feel like I saw a logger being used somewhere. If so let's use it for consistency.

File: lsp/markdown/completion/configDeclare.md [hunk 3]
```diff
@@ -0,0 +1,9 @@
+Snippet for declaring a config variable.
+
+```go
+var defaultUser = ftl.Config[string]("default")
+```
+
+See https://tbd54566975.github.io/ftl/docs/reference/secretsconfig/
+---
+var ${1:configVar} = ftl.Config[${2:Type}](${3:default})
```
Comment (alecthomas) [inline lsp/markdown/completion/configDeclare.md:9]: The parameter isn't the default, it's the name of the secret, so it can just default to `configVar`

File: lsp/markdown/completion/configGet.md [hunk 4]
```diff
@@ -0,0 +1,9 @@
+Snippet for getting a config variable.
+
+```go
+username = defaultUser.Get(ctx)
+```
+
+See https://tbd54566975.github.io/ftl/docs/reference/secretsconfig/
+---
+${1:value} := ${2:configVar}.Get(ctx)
```
Comment (alecthomas) [inline lsp/markdown/completion/configGet.md:9]: I'm not sure these snippets add much value, WDYT? Normal completion on the config var will show people what to do? Though I guess it can't hurt?

File: lsp/markdown/completion/cron.md [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+//ftl:cron 6h
+func EverySixHours(ctx context.Context) {}
+```
+
+See https://tbd54566975.github.io/ftl/docs/reference/cron/
+---
+
+//ftl:cron ${1:Schedule}
+func ${2:Name}(ctx context.Context) {
```
Comment (alecthomas) [inline lsp/markdown/completion/cron.md:15]: This needs to return an error.

File: lsp/markdown/completion/cron.md [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+func Hourly(ctx context.Context) {}
+
+//ftl:cron 6h
+func EverySixHours(ctx context.Context) {}
+```
+
+See https://tbd54566975.github.io/ftl/docs/reference/cron/
+---
+
+//ftl:cron ${1:Schedule}
```
Comment (alecthomas) [inline lsp/markdown/completion/cron.md:14]: I think it might be better to split this snippet into two? One where we explicitly list each component of the full form, eg. `${1:minute} ${2:hour} ...` and one for the short form.

File: lsp/markdown/completion/cron.md [hunk 7]
```diff
@@ -0,0 +1,18 @@
+Snippet for declaring a cron job.
```
Comment (alecthomas) [inline lsp/markdown/completion/cron.md:1]: I don't think the snippet text should say it's a snippet, instead it should describe what it does and maybe what a cron job is.

File: lsp/markdown/completion/configGet.md [hunk 8]
```diff
@@ -0,0 +1,9 @@
+Snippet for getting a config variable.
```
Comment (alecthomas) [inline lsp/markdown/completion/configGet.md:1]: Same as elsewhere - the snippet shouldn't describe that it's a snippet, it should describe what a config variable is/does.

File: lsp/markdown/completion/configDeclare.md [hunk 9]
```diff
@@ -0,0 +1,9 @@
+Snippet for declaring a config variable.
```
Comment (alecthomas) [inline lsp/markdown/completion/configDeclare.md:1]: Describe what this is doing and what a config value is.

File: lsp/markdown/completion/enumType.md [hunk 10]
```diff
@@ -1,4 +1,4 @@
-Snippet for defining a type enum (sum types).
+Snippet for declare a type enum (sum types).
```
Comment (alecthomas) [inline lsp/markdown/completion/enumType.md:1]: Grammar, and more descriptive.

File: lsp/markdown/completion/cron.md (hunk 7 above)
Comment (alecthomas) [reply lsp/markdown/completion/cron.md:1]: Ah I see you copied the existing text, which I must have missed in Wes's PR. Mind fixing those up too?

File: lsp/markdown/completion/ingress.md [hunk 11]
```diff
@@ -0,0 +1,39 @@
+Snippet for declaring an ingress function.
```
Comment (alecthomas) [inline lsp/markdown/completion/ingress.md:1]: Same as above, describe what an ingress function is.

File: lsp/markdown/completion/secretGet.md [hunk 12]
```diff
@@ -0,0 +1,9 @@
+Snippet for getting a secret.
```
Comment (alecthomas) [inline lsp/markdown/completion/secretGet.md:1]: As above, do we think these snippets are useful?

File: lsp/markdown/completion/retry.md [hunk 13]
```diff
@@ -0,0 +1,9 @@
+Snippet for retrying an async operation.
```
Comment (alecthomas) [inline lsp/markdown/completion/retry.md:1]: This should describe what it is, and more importantly where it is applicable, as it's only used in limited situations.

File: lsp/markdown/completion/pubSubPublish.md [hunk 14]
```diff
@@ -0,0 +1,10 @@
+Snippet for publishing an event to a topic.
+
+```go
+invoicesTopic.Publish(ctx, Invoice{...})
+```
+
+See https://tbd54566975.github.io/ftl/docs/reference/pubsub/
+---
+${1:topicVar}.Publish(ctx, ${2:Type}{${3:...}})
```
Comment (alecthomas) [inline lsp/markdown/completion/pubSubPublish.md:9]: As with the secret/config getters...is this useful?

File: lsp/markdown/completion/ingress.md [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+type ${1:Func}Request struct {
+	${2:Field} ${3:Type} `json:"${4:field}"`
+}
+
+type ${1:Func}Response struct {
+	${5:Field} ${6:Type} `json:"${7:field}"`
+}
+
+//ftl:ingress ${8:GET} ${9:/url/path}
+func ${1:Func}(ctx context.Context, req builtin.HttpRequest[${1:Func}Request]) (builtin.HttpResponse[${1:Func}Response, string], error) {
```
Comment (alecthomas) [inline lsp/markdown/completion/ingress.md:33]: Nice.

File: lsp/completion.go (hunk 2 above)
Comment (gak) [reply lsp/completion.go:89]: This is run in global scope. Should I spin up one with `ContextWithNewDefaultLogger`?

Or I can just panic like the previous check.

File: lsp/markdown/completion/configGet.md (hunk 4 above)
Comment (gak) [reply lsp/markdown/completion/configGet.md:9]: I did consider that. Yeah it'll make LSP maintenance lower for us too.

File: lsp/completion.go (hunk 2 above)
Comment (alecthomas) [reply lsp/completion.go:85]: Ah yeah, panic

**Review by alecthomas — APPROVED** [review]
