### PR TITLE
fix: validate configs and secrets against the schema before setting

### LINKED ISSUE #1800: Validate secrets/config against the schema before setting the value
Now that we (mostly) have secrets/config going through the controller, we should add validation when setting them. For the controller version the schema can be loaded from the DB, but for the purely local case we'd need to load the schema from the build directory. I can't recall if we have any generic "validate this data against this schema" mechanism, so we might need to implement that first if not.

This might be contingent on #1775

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1800

### CODE REVIEW

File: backend/controller/admin/admin.go [hunk 1]
```diff
@@ -101,8 +109,13 @@ func configProviderKey(p *ftlv1.ConfigProvider) string {
 
 // ConfigSet sets the configuration at the given ref to the provided value.
 func (s *AdminService) ConfigSet(ctx context.Context, req *connect.Request[ftlv1.SetConfigRequest]) (*connect.Response[ftlv1.SetConfigResponse], error) {
+	err := s.validateAgainstSchema(ctx, false, cf.NewRef(*req.Msg.Ref.Module, req.Msg.Ref.Name), req.Msg.Value)
```
Comment (alecthomas) [inline backend/controller/admin/admin.go:112]: Module is optional in the proto, so this (and elsewhere) will panic. Use the getter instead.

File: backend/controller/admin/admin.go [hunk 2]
```diff
@@ -207,3 +225,50 @@ func (s *AdminService) SecretUnset(ctx context.Context, req *connect.Request[ftl
 	}
 	return connect.NewResponse(&ftlv1.UnsetSecretResponse{}), nil
 }
+
+func (s *AdminService) validateAgainstSchema(ctx context.Context, isSecret bool, ref cf.Ref, value json.RawMessage) error {
+	sch, err := s.schr.GetActiveSchema(ctx)
```
Comment (alecthomas) [inline backend/controller/admin/admin.go:230]: We can't validate a global, so we may as well early exit here. We should come up with a solution for that, can you file a ticket please?

File: backend/controller/admin/admin.go [hunk 3]
```diff
@@ -207,3 +225,50 @@ func (s *AdminService) SecretUnset(ctx context.Context, req *connect.Request[ftl
...
+	} else {
+		decl, ok := decl.(*schema.Config)
+		if !ok {
+			return fmt.Errorf("%q is not a config declaration", ref.Name)
+		}
+		fieldType = decl.Type
+	}
+
+	var v any
+	dec := json.NewDecoder(bytes.NewReader(value))
```
Comment (alecthomas) [inline backend/controller/admin/admin.go:261]: This will have to use `go-runtime/encoding` - which we still need to pull out of the runtime.

File: backend/controller/admin/admin_test.go [hunk 4]
```diff
@@ -140,3 +142,121 @@ func testAdminSecrets(
...
+		Value:    buffer.Bytes(),
+	}))
+	assert.EqualError(t, err, expectedError)
+}
+
+// nolint
+func testSetSecret(t testing.TB, ctx context.Context, admin *AdminService, module string, name string, jsonVal any, expectedError string) {
+	t.Helper()
+	var buffer bytes.Buffer
+	enc := json.NewEncoder(&buffer)
```
Comment (alecthomas) [inline backend/controller/admin/admin_test.go:252]: Same here and elsewhere - we should be using `go-runtime/encoding`

Comment (alecthomas) [reply backend/controller/admin/admin_test.go:252]: But also, FYI if you just need `[]byte` you can use `json.Marshal()`

File: backend/controller/admin/local_client.go [hunk 5]
```diff
@@ -13,8 +22,46 @@ type localClient struct {
...
+	}
+	modules, err := buildengine.DiscoverModules(ctx, projConfig.AbsModuleDirs())
+	if err != nil {
+		return nil, fmt.Errorf("could not discover modules: %w", err)
+	}
+
+	var pbModules []*schemapb.Module
+	for _, m := range modules {
+		deployDir := m.Config.Abs().DeployDir
+		schemaPath := filepath.Join(deployDir, m.Config.Schema)
```
Comment (alecthomas) [inline backend/controller/admin/local_client.go:50]: This is joining two absolute paths, you need to just use `m.Config.Schema` directly. Can you write an integration test for this?

File: backend/controller/admin/local_client.go [hunk 6]
```diff
@@ -13,8 +22,46 @@ type localClient struct {
...
+		content, err := os.ReadFile(schemaPath)
```
Comment (alecthomas) [inline backend/controller/admin/local_client.go:51]: There's a function in `schema` to load a module schema directly from disk.

File: backend/controller/admin/local_client.go [hunk 7]
```diff
@@ -13,8 +22,46 @@ type localClient struct {
...
+type diskSchemaRetriever struct{}
+
 func newLocalClient(ctx context.Context) *localClient {
 	cm := configuration.ConfigFromContext(ctx)
 	sm := configuration.SecretsFromContext(ctx)
-	return &localClient{NewAdminService(cm, sm)}
+	return &localClient{NewAdminService(cm, sm, &diskSchemaRetriever{})}
+}
+
+func (s *diskSchemaRetriever) GetActiveSchema(ctx context.Context) (*schema.Schema, error) {
```
Comment (alecthomas) [inline backend/controller/admin/local_client.go:33]: Unless we compile these, I don't think we can rely on these schemas being present, which means we shouldn't use them for validation in the local case at all I suspect, as compiling before setting a secret would be quite irritating.

I can't think of a better solution right now.

File: backend/controller/admin/local_client.go (hunk 5 above)
Comment (alecthomas) [reply backend/controller/admin/local_client.go:50]: Actually disregard that, per the other comment.

**Comment by alecthomas** [comment]
BTW @safeer you probably picked up on a bunch of these problems/limitations while writing the PR. It's okay if you think implementing /fixing a ticket isn't possible, or doesn't make sense - the underlying ticket is almost never fully thought through, it's just identifying a problem and often proposing a potential solution, but it's not set in stone.

File: backend/controller/admin/admin.go (hunk 1 above)
Comment (safeer) [reply backend/controller/admin/admin.go]: These calls all seem to have been working in prod, but I fixed them up. Good catch!

File: backend/controller/admin/local_client.go (hunk 5 above)
Comment (safeer) [reply backend/controller/admin/local_client.go:50]: `m.Config.Schema` is a relative path, not absolute, and this code path is tested in `TestAdminService` but I can make it more explicit

File: backend/controller/admin/local_client.go (hunk 7 above)
Comment (safeer) [reply backend/controller/admin/local_client.go:33]: Gotcha. I thought schema.pb was always available for a module by this point, bad assumption on my part!

File: backend/controller/admin/local_client.go (hunk 5 above)
Comment (alecthomas) [reply backend/controller/admin/local_client.go:50]: Sorry I saw you were using `.Abs()` and assumed you were using it for both. What I should have said is that  as you're using`m.Config.Abs()`, you should just use `.Schema` from that, which will be absolute already.

**Comment by safeer** [comment]
This now does best effort validation; without a controller, it will validate using the on-disk schema only if it exists, and it does not validate global secrets/configs. Tests cover missing schema, schema.pb artifact, and dal-stored schema.

**Review by alecthomas — APPROVED** [review]
