### PR TITLE
fix: parallelize deployments

### LINKED ISSUE #1031: Add queuing for deployments to speed up builds
Currently builds have to wait for a previous deployment to finish before they can run. 

We should be able to build and queue the deployment, so we can move onto the next build without waiting.

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1031

Introduces non-blocking deploys so that they can while other modules are build. 

BEFORE (20s cold, 11s warm):
Screenshot 2024-03-07 at 1 28 09 PM

AFTER (16s cold, 8s warm):
Screenshot 2024-03-07 at 1 29 23 PM

### CODE REVIEW

File: buildengine/engine.go [hunk 1]
```diff
@@ -223,13 +221,41 @@ func (e *Engine) Dev(ctx context.Context, period time.Duration) error {
...
-	if err != nil {
-		return err
+	if len(modules) == 0 {
+		modules = maps.Keys(e.modules)
 	}
-	return nil
+
+	deployQueue := make(chan Module, len(modules))
+	wg, ctx := errgroup.WithContext(ctx)
+	wg.SetLimit(runtime.NumCPU())
```
Comment (wesbillman) [inline buildengine/engine.go:230]: I tried to follow the pattern in the `build` command to limit the concurrency. Not 100% sure if this is the best solution of if there's something else I should try here.

Comment (alecthomas) [reply buildengine/engine.go:230]: You probably don't need the same limit for deploys, it will be mostly network bound I think. You can probably remove the limit for now.

File: buildengine/engine.go [hunk 2]
```diff
@@ -223,13 +221,41 @@ func (e *Engine) Dev(ctx context.Context, period time.Duration) error {
...
+				return nil
+			case <-ctx.Done():
+				return ctx.Err()
+			}
+		}, modules...)
+	})
+
+	for i := 0; i < len(modules); i++ {
+		wg.Go(func() error {
+			for module := range deployQueue {
```
Comment (alecthomas) [inline buildengine/engine.go:247]: This should be a for loop with a select inside, that checks `<-ctx.Done()` as the other Go call does.

**Review by alecthomas — APPROVED** [review]
