### PR TITLE
fix: increase parser lookahead

### LINKED ISSUE #1507: Parse a module that has more than 2 lines of comments for a Secret causes a parse error
Saw this in TestParseModule when working on #1505 but didn't investigate.

```
// A comment
module todo {
  // A config value
  config configValue String
  // Shhh
  // This is a secret
  // It should not be shared
  secret secretValue String
```

```
schema_test.go:459: Did not expect an error but got:
        9:3: unexpected token "secret" (expected "data" <ident> ("<" TypeParameter ("," TypeParameter)* ">")? "{" Field* "}" Metadata*)
```

### PR DESCRIPTION
**Pull request by alecthomas**
Fixes #1507. I'm really surprised we haven't hit this previously.

### CODE REVIEW

File: backend/schema/parser.go [hunk 1]
```diff
@@ -47,7 +47,8 @@ var (
 		participle.Lexer(Lexer),
 		participle.Elide("Whitespace"),
 		participle.Unquote(),
-		participle.UseLookahead(2),
+		// Increase lookahead to allow comments to be attached to the next token.
+		participle.UseLookahead(participle.MaxLookahead),
```
Comment (alecthomas) [inline backend/schema/parser.go:51]: Testing comment issue creation.

File: backend/schema/parser.go [hunk 2]
```diff
@@ -47,7 +47,8 @@ var (
 		participle.Lexer(Lexer),
 		participle.Elide("Whitespace"),
 		participle.Unquote(),
-		participle.UseLookahead(2),
+		// Increase lookahead to allow comments to be attached to the next token.
```
Comment (alecthomas) [inline backend/schema/parser.go:50]: Another comment.

**Comment by alecthomas** [comment]
Moo.

**Comment by alecthomas** [comment]
Moar

File: backend/schema/parser.go (hunk 2 above)
Comment (alecthomas) [inline backend/schema/parser.go:50]: First comment

File: backend/schema/parser.go (hunk 1 above)
Comment (alecthomas) [inline backend/schema/parser.go:51]: Second comment

File: backend/schema/parser.go (hunk 2 above)
Comment (alecthomas) [inline backend/schema/parser.go:50]: Test

File: backend/schema/parser.go (hunk 1 above)
Comment (alecthomas) [inline backend/schema/parser.go:51]: Moo

File: backend/schema/parser.go (hunk 2 above)
Comment (alecthomas) [inline backend/schema/parser.go:50]: Test

File: backend/schema/parser.go (hunk 1 above)
Comment (alecthomas) [inline backend/schema/parser.go:51]: Comment

File: backend/schema/parser.go (hunk 2 above)
Comment (alecthomas) [inline backend/schema/parser.go:50]: Test

File: backend/schema/parser.go (hunk 1 above)
Comment (alecthomas) [inline backend/schema/parser.go:51]: Test

**Review by alecthomas — COMMENTED** [review]
Moo

File: backend/schema/parser.go (hunk 2 above)
Comment (alecthomas) [inline backend/schema/parser.go:50]: Test
