### PR TITLE
fix: don't log at error level in lease timeout

### LINKED ISSUE #2133: Lower ASM follower sync error log level for expected initial case
This is expected when new controllers are brought up but for 10s or so the previous controller still has a lease.
The initial errors are confusing as they make it look like something unexpected is happening. We should only error after a certain number of errors or after a certain amount of time.
```
Error syncing asm: asm/follower/http://10.2.110.252:8892: error getting secrets list from leader: permission_denied: RBAC: access denied
```

### PR DESCRIPTION
**Pull request by stuartwdouglas**
We don't want error alerts if a controller is just failing over, this PR adds some infrasturcture to allow for a lower level of error reporting when the errors all occur within the lease TTL.

fixes #2133

### CODE REVIEW

File: backend/controller/leader/leader.go [hunk 1]
```diff
@@ -220,3 +220,72 @@ func (c *Coordinator[P]) retireFollower() {
...
+		// within the lease timeout, this indicates transient errors are happening
+		if c.recordedSuccessTime.Ok() {
+			return true
+		}
+		if errorTime.Add(c.leaseTTL).After(time.Now()) {
+			// Within the lease window, it will probably be resolved when a new leader is elected
+			return false
+		}
+		return true
+	} else {
```
Comment (matt2e) [inline backend/controller/leader/leader.go:268]: Looks like it'd be neater to do `if !ok` and then return early

File: common/configuration/asm_follower.go [hunk 2]
```diff
@@ -51,7 +53,14 @@ func (f *asmFollower) sync(ctx context.Context, values *xsync.MapOf[Ref, SyncedV
 		IncludeValues: &includeValues,
 	}))
 	if err != nil {
-		return fmt.Errorf("error getting secrets list from leader: %w", err)
+		if f.errorFilter.ReportLeaseError() {
```
Comment (matt2e) [inline common/configuration/asm_follower.go:56]: I do think this is too general, like was mentioned on this morning's call. What @alecthomas said about responses that include errors vs network errors feels like a good way to differentiate.

**Review by matt2e — CHANGES_REQUESTED** [review]
Looks like a good direction @stuartwdouglas as this does feel like something that would be useful for more things that end up using leader/follower.

I think you mentioned on the call this morning that you thought it might be useful for anything that used leases? I'm less sure about that but maybe I havent thought of use cases, or maybe I'm misremembering. Either way my feel is what you've done in the code here is the right place, but I'm interested to hear if you had other ideas?

File: common/configuration/asm_follower.go (hunk 2 above)
Comment (stuartwdouglas) [reply common/configuration/asm_follower.go:56]: Do we have an example somewhere of how to determine the type of error? The library docs mention connect.Error but that does not seem to match what is in the datadog logs.

I never thought I would miss Java checked exceptions, but they do make situations like this easier.

Comment (wesbillman) [reply common/configuration/asm_follower.go:56]: Maybe something like this: https://github.com/TBD54566975/ftl/blob/main/backend/controller/ingress/handler.go#L55-L62

Comment (stuartwdouglas) [reply common/configuration/asm_follower.go]: Thanks, I have updated it to use the return codes to decide on if it should attempt to filter

**Comment by alecthomas** [comment]
@matt2e are you happy with this now?

**Review by matt2e — APPROVED** [review]
👏 looks good
