### PR TITLE
fix: no longer projecting int64 to FTL Int

### LINKED ISSUE #1920: No error for int64 not being a valid FTLType at build time
```
type ExampleData struct {
	InvalidFieldType int64
}
```
This should error at build time because FTL does not support int64.
We should fix this for all the places where int64 could turn up, not just within structs, and also look at other types we don't support (float64 etc)

### PR DESCRIPTION
**Pull request by jonathanj-square**
fixes #1920

`int64` no longer projected to the FTL Int data type; `int` must be used instead.

### CODE REVIEW

File: go-runtime/compile/schema.go [hunk 1]
```diff
@@ -1284,9 +1285,13 @@ func visitType(pctx *parseContext, pos token.Pos, tnode types.Type, isExported b
 		case types.String:
 			return optional.Some[schema.Type](&schema.String{Pos: goPosToSchemaPos(pos)})
 
-		case types.Int, types.Int64:
+		case types.Int:
 			return optional.Some[schema.Type](&schema.Int{Pos: goPosToSchemaPos(pos)})
 
+		case types.Int64:
+			pctx.errors.add(tokenErrorf(1234, underlying.Name(), "int is not a supported type; specify int instead %s", underlying.Name()))
```
Comment (deniseli) [inline go-runtime/compile/schema.go:1292]: `int64 is not a supported type; instead, specify int for %q`. And friendly reminder to not forget about replacing `1234` with the position data :)

Comment (deniseli) [reply go-runtime/compile/schema.go:1292]: btw if you'd like to see how this error shows up for real, you can try adding it to `failing.go`. There's a test for it in `go-runtime/compile/schema_test.go`.

File: go-runtime/compile/schema.go [hunk 2]
```diff
@@ -1284,9 +1285,13 @@ func visitType(pctx *parseContext, pos token.Pos, tnode types.Type, isExported b
 		case types.String:
 			return optional.Some[schema.Type](&schema.String{Pos: goPosToSchemaPos(pos)})
 
-		case types.Int, types.Int64:
```
Comment (alecthomas) [inline go-runtime/compile/schema.go:1287]: Aha!

**Review by alecthomas — APPROVED** [review]
LGTM modulo comments @deniseli made

File: go-runtime/compile/schema.go (hunk 1 above)
Comment (jonathanj-square) [reply go-runtime/compile/schema.go:1292]: that was placeholder for sure! thanks for catching that. The error message does not need to be reported since the calling code reports a meaningful error when None is returned as the type. I've deleted the `Int64` case entirely.

Comment (deniseli) [reply go-runtime/compile/schema.go]: awesome!
