### PR TITLE
fix(bug): time range selection

### LINKED ISSUE #2612: Event page timeline dropdown not working
It seems like maybe a z-index issue or something, but I can't select different times in the dropdown anymore

Screenshot 2024-09-04 at 10 49 00 AM

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #2612 

Screenshot 2024-09-06 at 10 27 10 AM

### CODE REVIEW

File: frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx [hunk 1]
```diff
@@ -109,58 +109,54 @@ export const TimelineTimeControls = ({
...
+              transition
+              className={`z-10 mt-1 w-40 rounded-md ${panelColor} py-1 text-xs shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none`}
+            >
+              {Object.keys(TIME_RANGES).map((key) => {
+                const timeRange = TIME_RANGES[key]
+                return (
+                  <ListboxOption
+                    key={key}
+                    className={({ focus }) =>
+                      classNames(focus ? 'bg-indigo-600 text-white' : `${textColor}`, 'relative cursor-pointer select-none py-2 pl-3 pr-9')
```
Comment (deniseli) [inline frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx:133]: Could 
```
`${textColor}`
```
be just `textColor`?

**Review by deniseli — APPROVED** [review]
