### PR TITLE
fix: suppress noisy log spam when scaling runners

### LINKED ISSUE #534: When we terminate a runner don't spam cancel errors.
Like this type of stuff...

```
info:reconcileRunners: Removing runner: R0000000000000000000000E000
error:reconcileRunners: Error starting runner: context canceled: context canceled
warn:runner5: Stream handler failed, retrying in 100ms: context canceled
warn:runner5: Stream handler failed, retrying in 100ms: context canceled
error:controller0: Streaming RPC failed: invalid_argument: protocol error: incomplete envelope: stream error: stream ID 41; CANCEL: /xyz.block.ftl.v1.ControllerService/StreamDeploymentLogs
```

### PR DESCRIPTION
**Pull request by alecthomas**
Also added `--recreate` flag to `ftl serve`.

Fixes #534

Before:

```
info:reconcileRunners: Removing runner: R00000000000000000000002000
warn:runner0: Stream handler failed, retrying in 100ms: context canceled
warn:runner0: Stream handler failed, retrying in 100ms: context canceled
error:reconcileRunners: Error starting runner: context canceled: context canceled
error:controller0: Streaming RPC failed: invalid_argument: protocol error: incomplete envelope: stream error: stream ID 3; CANCEL: /xyz.block.ftl.v1.ControllerService/RegisterRunner
```

After:

```
info:reconcileRunners: Removing runner: R00000000000000000000002000
error:controller0: Streaming RPC failed: invalid_argument: protocol error: incomplete envelope: stream error: stream ID 9; CANCEL: /xyz.block.ftl.v1.ControllerService/StreamDeploymentLogs
```

There's still one error, but it seems more difficult to fix this one, and it seems more intermittent too.

### CODE REVIEW

File: cmd/ftl/cmd_serve.go [hunk 1]
```diff
@@ -132,14 +134,8 @@ func setupDB(ctx context.Context) (string, error) {
...
 	dsn := fmt.Sprintf("postgres://postgres:secret@localhost:%s/%s?sslmode=disable", strings.TrimSpace(string(port)), ftlContainerName)
-	dsnFlag := fmt.Sprintf("--dsn=%s", dsn)
 
-	if recreate {
-		logger.Infof("Initializing FTL schema")
-		err = exec.Command(ctx, logger.GetLevel(), ".", "ftl-initdb", "--recreate", dsnFlag).Run()
-	} else {
-		err = exec.Command(ctx, logger.GetLevel(), ".", "ftl-initdb", dsnFlag).Run()
-	}
+	_, err = databasetesting.CreateForDevel(ctx, dsn, recreate)
```
Comment (wesbillman) [inline cmd/ftl/cmd_serve.go:138]: Thank you! :)
