### PR TITLE
fix: add an FTL tag and filter ASM secrets

### LINKED ISSUE #1876: Add labels to all AWS secrets
1. Set the label `ftl`, and the module name if present.
2. Only allow retrieval/listing of secrets with the `ftl` label.

### PR DESCRIPTION
**Pull request by safeer**
Fixes #1876

### CODE REVIEW

**Comment by matt2e** [comment]
LGTM 👍
is `_ftl` preferred over `ftl`?

**Review by matt2e — APPROVED** [review]

File: common/configuration/asm_leader.go [hunk 1]
```diff
@@ -149,6 +155,9 @@ func (l *asmLeader) store(ctx context.Context, ref Ref, value []byte) (*url.URL,
 	_, err := l.client.CreateSecret(ctx, &secretsmanager.CreateSecretInput{
 		Name:         aws.String(ref.String()),
 		SecretString: aws.String(string(value)),
+		Tags: []types.Tag{
+			{Key: aws.String("_ftl"), Value: aws.String(ref.Module.Default("_"))},
```
Comment (alecthomas) [inline common/configuration/asm_leader.go:159]: Any reason for the `_`?

File: common/configuration/asm_leader.go [hunk 2]
```diff
@@ -54,6 +54,9 @@ func (l *asmLeader) sync(ctx context.Context, secrets *xsync.MapOf[Ref, cachedSe
 		out, err := l.client.ListSecrets(ctx, &secretsmanager.ListSecretsInput{
 			MaxResults: aws.Int32(100),
 			NextToken:  nextToken.Ptr(),
+			Filters: []types.Filter{
+				{Key: types.FilterNameStringTypeTagKey, Values: []string{"_ftl"}},
```
Comment (alecthomas) [inline common/configuration/asm_leader.go:58]: Let's pull the tag value out into a constant.

**Review by alecthomas — APPROVED** [review]
Nice!

File: common/configuration/asm_leader.go [hunk 3]
```diff
@@ -149,6 +155,9 @@ func (l *asmLeader) store(ctx context.Context, ref Ref, value []byte) (*url.URL,
 	_, err := l.client.CreateSecret(ctx, &secretsmanager.CreateSecretInput{
 		Name:         aws.String(ref.String()),
 		SecretString: aws.String(string(value)),
+		Tags: []types.Tag{
+			{Key: aws.String("ftl"), Value: aws.String(ref.Module.Default("_"))},
```
Comment (alecthomas) [inline common/configuration/asm_leader.go:159]: Can the value not be empty? `_` is actually a valid module name, so if it can't be empty it should at least be `-` which is not a valid identifier.

Comment (safeer) [reply common/configuration/asm_leader.go]: It can be empty, pushing a fix

**Comment by michaelneale** [comment]
nice! and much needed. Most AWS accounts will have many secrets in many formats
