### PR TITLE
fix: populate verb right panel and verb schema

### LINKED ISSUE #734: [ftl console] table fields mushing together
check out the destination and request columns in the screenshot.

image

will tackle this in a PR soon!

### LINKED ISSUE #1377: Update VerbPage in console
- [x] Make sure we show data structures
- [x] Fix UI for sending test messages
- [x] Fix UI overlap issues in table
- [x] Fix request graph/tracing
- [x] (Stretch) detect http ingress requests and make a better UI for them

### PR DESCRIPTION
**Pull request by wesbillman**
Updates:
- Populate right panel with ingress and calls
- Add verb schema tab to view the verb's schema
- Fix layout bugs on call list
- Refactor and reuse code

Fixes #734 
Fixes #1377 

Screenshot 2024-05-09 at 1 02 11 PM
Screenshot 2024-05-09 at 12 56 12 PM

### CODE REVIEW

File: backend/controller/console.go [hunk 1]
```diff
@@ -40,6 +40,26 @@ func (*ConsoleService) Ping(context.Context, *connect.Request[ftlv1.PingRequest]
 	return connect.NewResponse(&ftlv1.PingResponse{}), nil
 }
 
+func verbSchemaString(sch *schema.Schema, verb *schema.Verb) string {
+	verbString := ""
+	_ = schema.Visit(verb, func(n schema.Node, next func() error) error {
+		switch n := n.(type) {
+		case *schema.Ref:
```
Comment (alecthomas) [inline backend/controller/console.go:47]: How is this resolving transitive types? It looks like it only resolves a single ref, rather than recursively?

**Review by alecthomas — APPROVED** [review]
Looks good! But one question...

File: backend/controller/console.go (hunk 1 above)
Comment (wesbillman) [reply backend/controller/console.go:47]: ah yeah, lemme add a console test to verify/fix that.

File: backend/controller/console.go [hunk 2]
```diff
@@ -40,6 +40,40 @@ func (*ConsoleService) Ping(context.Context, *connect.Request[ftlv1.PingRequest]
...
+	if err != nil {
+		return "", err
+	}
+	err = visitNode(sch, verb.Response, &verbString)
+	if err != nil {
+		return "", err
+	}
+	verbString += verb.String()
+	return verbString, nil
+}
```
Comment (wesbillman) [inline backend/controller/console.go:75]: @alecthomas is this a reasonable approach?

Comment (alecthomas) [reply backend/controller/console.go:75]: What you had before was fine in terms of visiting all nodes recursively, but I don't think it follows `Ref`s under normal circumstances, which is something this will want to do.

Comment (alecthomas) [reply backend/controller/console.go:75]: What I mean is if you have this:

```
data User {
  name String
}

data Req {
  user User
}
```

The "user" field will be represented as a `Ref` in the schema, and I don't think (could be wrong) that will get visited under normal circumstances.

Comment (wesbillman) [reply backend/controller/console.go:75]: Yeah I think you're right. That's why I added that `visitNode` func so that I could visit the `Ref` as well. But maybe I should update the `schema.Visit` to follow these refs as well?

Comment (wesbillman) [reply backend/controller/console.go:75]: I'll merge this PR for the console updates and fixes and we can sync on this when you have a sec. Want to make sure I get this updated as needed. 👍
