### PR TITLE
fix: use shared .ftl folder for stubs

### LINKED ISSUE #1662: Codegen all known modules, not just dependencies
In a project with a bunch of modules, it's currently very annoying adding an import for an FTL module, because not all modules are codegenned into the build directory. You have to:

1. Go up to the import section and manually enter the import, eg. `import "ftl/foo"`
2. Go back to a code block and reference a symbol in this module so that `goimports` doesn't remove it, eg. `foo.Bar`
3. Save your code.
4. Wait for FTL to rescan your module and codegen the missing module.
5. Finally you can use the module.

I think it might be a lot simpler to codegen all modules into a global shared directory, and just add this directory to all `go.work` files. That way all known modules will be available at all times.

### LINKED ISSUE #1827: Rename `_ftl` directory to `.ftl`

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1662 
Fixes #1827

### CODE REVIEW

File: buildengine/engine.go [hunk 1]
```diff
@@ -614,6 +626,28 @@ func (e *Engine) build(ctx context.Context, moduleName string, builtModules map[
...
+	out map[string]*schema.Module,
+) error {
+	for _, module := range group {
+		if module == "builtin" {
+			continue // Skip the builtin module
+		}
+
+		meta, ok := e.moduleMetas.Load(module)
+		if !ok {
+			return fmt.Errorf("Module %q not found", module)
```
Comment (alecthomas) [inline buildengine/engine.go:642]: nit: errors shouldn't be upper cased

File: buildengine/engine_test.go [hunk 2]
```diff
@@ -16,7 +16,7 @@ func TestEngine(t *testing.T) {
 		t.SkipNow()
 	}
 	ctx := log.ContextWithNewDefaultLogger(context.Background())
-	engine, err := buildengine.New(ctx, nil, []string{"testdata/alpha", "testdata/other", "testdata/another"})
+	engine, err := buildengine.New(ctx, nil, t.TempDir(), []string{"testdata/alpha", "testdata/other", "testdata/another"})
```
Comment (alecthomas) [inline buildengine/engine_test.go:19]: Just a heads up that `t.TempDir()` will create a new tempdir each time it's called. Just make sure that's what you want.

File: cmd/ftl/cmd_new.go [hunk 3]
```diff
@@ -30,9 +31,10 @@ type newCmd struct {
 }
 
 type newGoCmd struct {
-	Replace map[string]string `short:"r" help:"Replace a module import path with a local path in the initialised FTL module." placeholder:"OLD=NEW,..." env:"FTL_INIT_GO_REPLACE"`
-	Dir     string            `arg:"" help:"Directory to initialize the module in."`
-	Name    string            `arg:"" help:"Name of the FTL module to create underneath the base directory."`
+	Replace   map[string]string `short:"r" help:"Replace a module import path with a local path in the initialised FTL module." placeholder:"OLD=NEW,..." env:"FTL_INIT_GO_REPLACE"`
+	Dir       string            `arg:"" help:"Directory to initialize the module in."`
+	Name      string            `arg:"" help:"Name of the FTL module to create underneath the base directory."`
+	GoVersion string
```
Comment (alecthomas) [inline cmd/ftl/cmd_new.go:37]: Delete

File: go-runtime/compile/build.go [hunk 4]
```diff
@@ -87,14 +93,15 @@ func (b ExternalModuleContext) NonMainModules() []*schema.Module {
 	return modules
 }
 
-const buildDirName = "_ftl"
+const buildDirName = ".ftl"
+const DefaultGoModVersion = "1.21"
```
Comment (alecthomas) [inline go-runtime/compile/build.go:97]: There should never be a need for something like this, we should always pull the Go version from the module's `go.mod` file.

File: cmd/ftl/cmd_new.go [hunk 5]
```diff
@@ -58,6 +60,8 @@ func (i newGoCmd) Run(ctx context.Context) error {
 
 	logger := log.FromContext(ctx)
 	logger.Debugf("Creating FTL Go module %q in %s", name, path)
+
+	i.GoVersion = compile.DefaultGoModVersion
```
Comment (alecthomas) [inline cmd/ftl/cmd_new.go:64]: This should never be needed, either pull it from the `go.mod` file or if that's _really_ not possible, from the `go` tool itself.

File: go-runtime/compile/devel.go [hunk 6]
```diff
@@ -8,9 +8,14 @@ import (
 	"github.com/TBD54566975/ftl/internal"
 )
 
+func mainWorkTemplateFiles() *zip.Reader {
+	return internal.ZipRelativeToCaller("main-work-template")
```
Comment (alecthomas) [inline go-runtime/compile/devel.go:12]: I don't see these files?

File: go-runtime/scaffolding/{{ .Name | camel | lower }}/go.mod.tmpl [hunk 7]
```diff
@@ -1,9 +1,9 @@
 module ftl/{{ .Name }}
 
-go 1.21
```
Comment (alecthomas) [inline go-runtime/scaffolding/{{ .Name | camel | lower }}/go.mod.tmpl:3]: OMG I wonder if this is the source of all those bugs we've seen ...

**Review by alecthomas — APPROVED** [review]
I imagine we don't really need tests, because if this wasn't working, all of our integration tests would fail.

File: buildengine/engine_test.go (hunk 2 above)
Comment (wesbillman) [reply buildengine/engine_test.go:19]: I had to look that up while I was working on this :)

File: go-runtime/compile/build.go (hunk 4 above)
Comment (wesbillman) [reply go-runtime/compile/build.go:97]: This was something I wanted to chat about. With this new shared setup, I'm not sure which version to use here. Given that we might be generating shared modules for multiple modules. Or in the initial case we're generating shared modules for just `builtins` so I don't have a go version to get from a module. In the other cases we're very likely generating a single shared `.ftl/go/modules` for a multiple modules, so I wasn't sure which go version to use there either.

The big one is the builtins though. That's what led to me adding this here, but it felt dirty for sure. I also added this central one so we could share it with the `cmd_new.go` go code that was using a hardcoded version in it's template.

File: cmd/ftl/cmd_new.go (hunk 5 above)
Comment (wesbillman) [reply cmd/ftl/cmd_new.go:64]: Yeah maybe we should use the go tool for this one too. Before this change the version was hard coded in the template.

File: go-runtime/compile/devel.go (hunk 6 above)
Comment (wesbillman) [reply go-runtime/compile/devel.go:12]: ahh maybe a .gitignore issue. I'll fix. Thanks!

File: cmd/ftl/cmd_new.go (hunk 3 above)
Comment (wesbillman) [reply cmd/ftl/cmd_new.go:37]: I added this one so that it could be used in the scaffolding template since that uses `newGoCmd` directly as it's context. Would it be better to create a new context and add what I need there for the template instead of using the `newGoCmd` for template context?

File: .gitignore [hunk 8]
```diff
@@ -18,12 +18,18 @@ examples/**/go.work
 examples/**/go.work.sum
 testdata/**/go.work
 testdata/**/go.work.sum
+
+# Leaving old _ftl for now to avoid old stuff getting checked in
 **/testdata/**/_ftl
 **/examples/**/_ftl
+**/testdata/**/.ftl
+**/examples/**/.ftl
+**/_ftl
```
[the remark this answers is not in the document]
Comment (wesbillman) [reply .gitignore:27]: I think I added the equivalent of what we had before with `_ftl` but maybe I'm missing something. I reordered these a bit to group them as well.

File: cmd/ftl/cmd_new.go (hunk 3 above)
Comment (alecthomas) [reply cmd/ftl/cmd_new.go:37]: Yes, if you need it in the context but it's not a flag, it shouldn't be in the flag struct.

File: go-runtime/compile/build.go (hunk 4 above)
Comment (alecthomas) [reply go-runtime/compile/build.go:97]: Ah good question. In that case we should use the highest version.

File: cmd/ftl/cmd_new.go (hunk 5 above)
Comment (alecthomas) [reply cmd/ftl/cmd_new.go:64]: Ah yes this is for `ftl new` - in that case it should definitely use the Go tool.

File: .gitignore (hunk 8 above)
[the remark this answers is not in the document]
Comment (alecthomas) [reply .gitignore:27]: No you added `**/_ftl` and `**/.ftl`, which shouldn't be there. It's the reason why your new template dir is missing. They need to be removed.

**Comment by alecthomas** [comment]
Let's not forget about this, looking forward to it!

**Review by alecthomas — APPROVED** [review]
Absolutely mammoth effort, thanks Wes :)
