### PR TITLE
fix: external_module.go with sinks/sources build failures

### LINKED ISSUE #1095: Build fails when importing another module which doesn't use go-runtime/ftl
Getting this build error when building a module which imports another module:
../modules/two/external_module.go:8:3: "github.com/TBD54566975/ftl/go-runtime/ftl" imported and not used

I worked around it by making use of ftl somehow, like by including an Option value somewhere

### PR DESCRIPTION
**Pull request by matt2e**
Fixes #1095

Sink & Source verbs would have a schema like
```
verb returnsUser(Unit) two.UserResponse
```
but the scaffolded `external_module.go` version of it would be:
```
func ReturnsUser(ctx context.Context) (UserResponse, error)
```

When generating imports, we were finding `schema.Unit` in the verb which triggered an inclusion of ftl
This caused the exernal module to fail to build because ftl was not being used by the generated code.

This fix now skips any unit in the schema if the parent is a verb

### CODE REVIEW

**Comment by matt2e** [comment]
Looks like this is not an issue in Kotlin

File: backend/schema/visit.go [hunk 1]
```diff
@@ -15,11 +15,16 @@ func Visit(n Node, visit func(n Node, next func() error) error) error {
 // VisitExcludingMetadataChildren visits all nodes in the schema except the children of metadata nodes.
 // This is used when generating external modules to avoid adding imports only referenced in the bodies of
 // stubbed verbs.
-func VisitExcludingMetadataChildren(n Node, visit func(n Node, next func() error) error) error {
-	return visit(n, func() error {
+func VisitExcludingMetadataChildren(n Node, visit func(n Node, parents []Node, next func() error) error) error {
+	return innerVisitExcludingMetadataChildren(n, []Node{}, visit)
+}
+
+func innerVisitExcludingMetadataChildren(n Node, parents []Node, visit func(n Node, parents []Node, next func() error) error) error {
```
Comment (alecthomas) [inline backend/schema/visit.go:22]: I think it would be simpler to type switch on `Verb`, manually call `Visit()` on the Verb's children iff they're not Unit and don't call `next()` in that case.

Comment (matt2e) [reply backend/schema/visit.go:22]: Isn't that an odd separation of concerns though? As in the needs of a specific go scaffolding use case compared to `schema/visit.go` providing ways to traverse the graph.
Currently this is also called when scaffolding Kotlin (which to be fair, might not be affected by a change like that, not 100% sure).

Comment (alecthomas) [reply backend/schema/visit.go:22]: Ah I see what you're saying, but no - this is supposed to be universal. It should be true in Kotlin too.

**Review by alecthomas — APPROVED** [review]
