### PR TITLE
fix: inject timeline client instead of using ctx

### LINKED ISSUE #3704: Pass `timeline` client into cron at start rather than grabbing it from context
Then we can get rid of grabbing it from context here: https://github.com/TBD54566975/ftl/blob/main/backend/cron/service.go#L135

There might be other services that need a similar change.

### LINKED ISSUE #3708: Timeline client should be passed around rather then attached to context

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #3708
Fixes #3704

### CODE REVIEW

File: backend/timeline/client.go [hunk 1]
```diff
@@ -40,18 +40,6 @@ func NewClient(ctx context.Context, endpoint *url.URL) *Client {
 	return client
 }
 
-func ContextWithClient(ctx context.Context, client *Client) context.Context {
```
Comment (worstell) [inline backend/timeline/client.go:43]: can delete line 23 as well (`type timelineContextKey struct{}`)

**Review by worstell — APPROVED** [review]
