### PR TITLE
fix: use body as root for ingress verb form fix console issue

### LINKED ISSUE #1863: Console should not require "body" in the form for http requests
```go
type EchoRequest = builtin.HttpRequest[builtin.Empty]

type Message struct {
	Message string `json:"message"`
}
type EchoResponse = builtin.HttpResponse[Message, ftl.Unit]
```

Will show the raw `body` etc. in the console instead of having the root be the body. This should work given that Headers are on their own tab.

So the `Body` tab for a http ingress should just be the ... `body` of the request.

```json
{}
```

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1863

### CODE REVIEW

File: backend/controller/console.go [hunk 1]
```diff
@@ -100,7 +101,7 @@ func (c *ConsoleService) GetModules(ctx context.Context, req *connect.Request[pb
 				v := decl.ToProto().(*schemapb.Verb)
 				verbSchema := schema.VerbFromProto(v)
 				var jsonRequestSchema string
-				if verbSchema.Request == nil {
+				if verbSchema.Request != nil {
```
Comment (wesbillman) [inline backend/controller/console.go:104]: 🤦

Comment (alecthomas) [reply backend/controller/console.go:104]: 😮

**Review by alecthomas — APPROVED** [review]
