### PR TITLE
Fix source and dest fields on metrics interceptor

### LINKED ISSUE #92: Source and Dest aren't correct for FTL calls
Screenshot 2023-07-05 at 3 54 35 PM

Calls to `time.time` should not have a `source` value (should be NULL in db)

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #92 

Screenshot 2023-07-10 at 10 32 24 AM

### CODE REVIEW

File: observability/interceptor.go [hunk 1]
```diff
@@ -49,11 +48,14 @@ func (i *Interceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
...
 		}
 
-		if verb := req.Header().Get(headers.VerbHeader); verb != "" {
-			metricsErr := i.recordVerbCallMetrics(ctx, verb, start, req.Header())
-			if metricsErr != nil {
-				logger.Errorf(metricsErr, "Failed to record metrics for verb: %s", verb)
-			}
+		callers, err := headers.GetCallers(req.Header())
+		if err != nil {
+			logger.Errorf(err, "Failed to get callers from headers")
```
Comment (alecthomas) [inline observability/interceptor.go:53]: Why is this logged? If there's an invalid header, which is the only error that can occur, this should return an error.
