### PR TITLE
fix: tabs hanging when more than 3 are open

### LINKED ISSUE #448: Opening 3 tabs on the console causes it to hang
Is there a concurrent connection limit/issue here? It seems like 3 tabs is the limit

@alecthomas do have any ideas on why this might happen

https://github.com/TBD54566975/ftl/assets/51647/b9ca6b9c-7431-4c96-82eb-f98600e8baa5

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #448 

https://github.com/TBD54566975/ftl/assets/51647/e72d6649-5ecd-409b-a904-1abb20223e76

### CODE REVIEW

File: console/client/src/hooks/use-schema.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+          return
+        }
+
+        const schemaMap = new Map<string, PullSchemaResponse>()
+        for await (const response of client.pullSchema(
+          {},
+          {
+            signal: abortController.signal,
+          },
+        )) {
```
Comment (wesbillman) [inline console/client/src/hooks/use-schema.ts:29]: This is the key change here on this PR. For some reason, `pullSchema` is perfectly happy with `signal` being passed in the first argument 🤷

File: console/client/package.json [hunk 2]
```diff
@@ -26,9 +26,9 @@
   ],
   "source": "index.html",
   "dependencies": {
-    "@bufbuild/connect": "0.12.0",
-    "@bufbuild/connect-web": "0.12.0",
-    "@bufbuild/protobuf": "1.3.0",
+    "@buf/connectrpc_eliza.connectrpc_es": "^1.1.2-20230913231627-233fca715f49.1",
```
Comment (alecthomas) [inline console/client/package.json:29]: Isn't this a demo app?

https://connectrpc.com/demo/

**Review by alecthomas — APPROVED** [review]

File: console/client/package.json (hunk 2 above)
Comment (wesbillman) [reply console/client/package.json:29]: Lol, totally is. I got it from here:
https://connectrpc.com/docs/web/getting-started#generating-the-client
