### PR TITLE
fix: explicitly suppress GRPC debug logs

### LINKED ISSUE #632: gRPC is still logging periodically
eg. these messages seem to get logged every two hours for some reason

```
07:30:04.241 [grpc-nio-worker-ELG-1-1] DEBUG io.grpc.netty.NettyServerHandler -- [id: 0x3d4b9476, L:/127.0.0.1:34427 - R:/127.0.0.1:40232] INBOUND PING: ack=true bytes=57005
[id: 0x3d4b9476, L:/127.0.0.1:34427 - R:/127.0.0.1:40232] OUTBOUND PING: ack=false bytes=57005


```

### PR DESCRIPTION
**Pull request by worstell**
fixes #632

### CODE REVIEW

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt [hunk 1]
```diff
@@ -67,6 +67,9 @@ class Logging {
       val rootLogger = logger(Logger.ROOT_LOGGER_NAME)
       val rootLevelCfg = Level.valueOf(System.getenv("LOG_LEVEL") ?: DEFAULT_LOG_LEVEL)
       rootLogger.level = rootLevelCfg
+
+      // Explicitly set log level for grpc-netty
+      logger("io.grpc.netty").level = Level.INFO
```
Comment (alecthomas) [inline kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt:72]: I think make this WARN, half of the logs are coming through as INFO:

image

Which, related, looks like it's not being logged at the correct level for some reason. It looks like it's not using the custom JSON log formatter.

**Review by alecthomas — APPROVED** [review]

File: kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt (hunk 1 above)
Comment (worstell) [reply kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt]: i _think_ this change should also fix the JSON formatting, the `logger("io.grpc.netty")` invocation explicitly adds an appender for this class so should force it to inherit the root logging configs that it doesn't seem to be currently for some reason

Comment (alecthomas) [reply kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt]: Ah nice!
