### PR TITLE
fix: detects cyclical dependencies and produces a build error

### LINKED ISSUE #1745: Circular call results in `fatal error: stack overflow`
if i import `"ftl/B"` inside a go file in `A` module 
and `B` already depends on `A`
then this creates a circular dependency. 

pulling in this import while `just dev` is running results in `just dev` failing with stack overflow error. see error below (the full error is very long)

```bash
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0x140458d4350 stack=[0x140458d4000, 0x140658d4000]
fatal error: stack overflow

runtime stack:
runtime.throw({0x10144c530?, 0x100751d64?})
	runtime/panic.go:1023 +0x40 fp=0x16ff9ad20 sp=0x16ff9acf0 pc=0x10075a2d0
runtime.newstack()
	runtime/stack.go:1103 +0x460 fp=0x16ff9aed0 sp=0x16ff9ad20 pc=0x100776d60
runtime.morestack()
	runtime/asm_arm64.s:341 +0x70 fp=0x16ff9aed0 sp=0x16ff9aed0 pc=0x10078f6e0

goroutine 34438 gp=0x140065a0fc0 m=16 mp=0x14001a0a008 [running]:
runtime.deductAssistCredit(0x10?)
	runtime/malloc.go:1337 +0x7c fp=0x140458d4350 sp=0x140458d4350 pc=0x10072ff5c
runtime.mallocgc(0x10, 0x1021924a0, 0x1)
	runtime/malloc.go:1025 +0xe8 fp=0x140458d43e0 sp=0x140458d4350 pc=0x10072f6c8
runtime.growslice(0x103015d40, 0x1400cc45380?, 0x0?, 0x1400cc3d380?, 0x1021924a0)
	runtime/slice.go:250 +0x4c0 fp=0x140458d4440 sp=0x140458d43e0 pc=0x100774f00
github.com/TBD54566975/ftl/backend/schema.(*Field).schemaChildren(0x1400066dd80)
	github.com/TBD54566975/ftl/backend/schema/field.go:27 +0x70 fp=0x140458d44e0 sp=0x140458d4440 pc=0x100b74d40
github.com/TBD54566975/ftl/backend/schema.Visit.func1()
	github.com/TBD54566975/ftl/backend/schema/visit.go:8 +0x30 fp=0x140458d4520 sp=0x140458d44e0 pc=0x100b923e0
github.com/TBD54566975/ftl/backend/schema.(*Module).Imports.func1({0x1023a2448?, 0x1400066dd80?}, 0x140003db340?)
	github.com/TBD54566975/ftl/backend/schema/module.go:168 +0xd0 fp=0x140458d4560 sp=0x140458d4520 pc=0x100b7cf10
github.com/TBD54566975/ftl/backend/schema.Visit({0x1023a2448, 0x1400066dd80}, 0x1400cc12918)
	github.com/TBD54566975/ftl/backend/schema/visit.go:7 +0x8c fp=0x140458d4590 sp=0x140458d4560 pc=0x100b9237c
github.com/TBD54566975/ftl/backend/schema.Visit.func1()
...
```

### PR DESCRIPTION
**Pull request by jonathanj-square**
fixes #1745

buildGraph does not check for cycles as it walks dependency chains; this change detects a member of the cycle and reports an error identifying that member

### CODE REVIEW

**Comment by alecthomas** [comment]
Hah, that was me above, updating some automation 🤦

File: buildengine/engine.go [hunk 1]
```diff
@@ -189,6 +189,9 @@ func (e *Engine) Graph(projects ...ProjectKey) (map[string][]string, error) {
 
 func (e *Engine) buildGraph(key string, out map[string][]string) error {
 	var deps []string
+	if _, ok := out[key]; ok {
+		return fmt.Errorf("module %q contains a cyclical dependency", key)
```
Comment (matt2e) [inline buildengine/engine.go:193]: 🎉

**Review by matt2e — APPROVED** [review]

File: buildengine/engine.go (hunk 1 above)
Comment (jonathanj-square) [reply buildengine/engine.go:193]: turns out this is a little too simplistic of an approach - I'm going to iterate on this more. Because `buildGraph` explores fully resolved dependencies (such as `builtin`) this will result in a ton of false positives

Comment (jonathanj-square) [reply buildengine/engine.go]: updated to move the cycle detection code to the topological sort function.`buildGraph` now simply short circuits when encountering a modules that has already visited

**Review by wesbillman — APPROVED** [review]

File: buildengine/topological.go [hunk 2]
```diff
@@ -1,21 +1,22 @@
...
 
-// TopologicalSort returns a sequence of groups of modules in topological order
-// that may be built in parallel.
-func TopologicalSort(graph map[string][]string) [][]string {
+// TopologicalSort attempts to order the modules supplied in the graph based on
+// their topologically sorted order. A cycle in the module dependency graph
+// will cause this sort to be incomplete. The sorted modules are returned as a
+// sequence of `groups` of modules that may be built in parallel. The `unsorted`
+// modules impacted by a dependency cycle are listed in random order.
+func TopologicalSort(graph map[string][]string) (groups [][]string, unsorted []string) {
```
Comment (worstell) [inline buildengine/topological.go:15]: what's the reason for returning `unsorted` here instead of the `NewDependencyCycleError` explicitly?

File: backend/controller/console.go [hunk 3]
```diff
@@ -161,7 +161,10 @@ func (c *ConsoleService) GetModules(ctx context.Context, req *connect.Request[pb
 		})
 	}
 
-	sorted := buildengine.TopologicalSort(graph(sch))
+	sorted, unsorted := buildengine.TopologicalSort(graph(sch))
+	if len(unsorted) > 0 {
+		return nil, connect.NewError(connect.CodeInvalidArgument, buildengine.NewDependencyCycleError(unsorted))
+	}
```
[the remark this answers is not in the document]
Comment (jonathanj-square) [reply backend/controller/console.go]: updated to reflect your feedback

File: buildengine/topological.go (hunk 2 above)
Comment (jonathanj-square) [reply buildengine/topological.go]: currently all the callers next move is to call `NewDependencyCycleError` so returning an error instead of these details might be better - change applied
