### PR TITLE
fix: lsp/vs less spammy with error toast popups

### LINKED ISSUE #1806: LSP there are too many popups
When writing code and the dev server watching all changes as you go, it is usually the case that your code is very broken on occasion and causes the LSP server to spit out many errors as popups.

Find a way to reduce it. Maybe:
- The extension can remove all errors except the last.
- Clear all errors when a rebuild is successful so the user doesn't have to close anything. (#1706)
- Do not create popups if they are associated with a positional error.

### PR DESCRIPTION
**Pull request by gak**
Fixes #1806

### CODE REVIEW

**Comment by alecthomas** [comment]
Mmmmmm toast 🍞

File: buildengine/engine.go [hunk 1]
```diff
@@ -25,6 +25,20 @@ import (
...
 
+type CompilerBuildError struct {
+	err error
+}
+
+func (e CompilerBuildError) Error() string {
+	return e.err.Error()
+}
+
+func (e CompilerBuildError) Is(target error) bool {
```
Comment (alecthomas) [inline buildengine/engine.go:36]: I think it would be simpler just to implement `Unwrap() error { return e.err }` - the `errors` package functions will do the correct thing.

**Review by alecthomas — APPROVED** [review]
