### PR TITLE
fix: rebuild dependent modules when schema changes

### LINKED ISSUE #1032: Add flag to buildengine `WatchEvent` to indicate if it was a hash change or schema change
This will be useful so we only rebuild dependent modules when a module's schema changes. This will improve performance of the build system.

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #1032 

Schema change on the `time` module:
```sh
ftl dev examples/go --recreate

info:time: Building module
info:time: Deploying module
info: time's schema changed; redeploying: [echo]
info:echo: Building module
info:controller0: Stopped time-cbfb2a0492
info:controller0: Deployed time-e21924cdd1
info:echo: Deploying module
info:controller0: Stopped echo-040fbeef14
info:controller0: Deployed echo-be607675b7
```

Schema change on the `productcatalog` module:
```sh
ftl dev ../ftl-examples/online-boutique/backend/services examples/go --recreate

info:productcatalog: Building module
info:productcatalog: Deploying module
info: productcatalog's schema changed; redeploying: [checkout recommendation]
info:recommendation: Building module
info:checkout: Building module
info:controller0: Stopped productcatalog-18dcbb6b02
info:controller0: Deployed productcatalog-d1d5fc9afd
info:recommendation: Deploying module
info:checkout: Deploying module
info:controller0: Stopped checkout-6c32b3cd6c
info:controller0: Stopped recommendation-c37d4bb336
info:controller0: Deployed checkout-e21c6b7419
info:controller0: Deployed recommendation-cd2ab7120f
```

Non-schema change to `time` module:
```sh
ftl dev examples/go --recreate

info:time: Building module
info:time: Deploying module
info:controller0: Stopped time-a77c27533b
info:controller0: Deployed time-243020e400
```

### CODE REVIEW

File: buildengine/engine.go [hunk 1]
```diff
@@ -185,6 +185,48 @@ func (e *Engine) watchForModuleChanges(ctx context.Context, period time.Duration
...
+		if err != nil {
+			logger.Errorf(err, "compute hash for %s failed", name)
+			return false
+		}
+		moduleHashes[name] = hash
+		return true
+	})
+
+	// Watch for schema changes from the FTL controller.
+	go rpc.RetryStreamingServerStream(ctx, backoff.Backoff{Max: time.Second}, &ftlv1.PullSchemaRequest{}, e.client.PullSchema, func(ctx context.Context, msg *ftlv1.PullSchemaResponse) error {
```
Comment (alecthomas) [inline buildengine/engine.go:195]: We're already pulling from the schema, why are we doing it twice instead of reusing the existing function?

**Review by alecthomas — CHANGES_REQUESTED** [review]

File: buildengine/engine.go (hunk 1 above)
Comment (wesbillman) [reply buildengine/engine.go:195]: No strong reason other than it seemed like the code was a bit more self contained in this function. But I can def refactor to reuse the existing one. I'll need to come up with a way to start getting updates after I do the deploy, but I'll see what works there.

Comment (alecthomas) [reply buildengine/engine.go:195]: For notifications I'd probably use a `pubsub.Topic`

Comment (wesbillman) [reply buildengine/engine.go:195]: Sweet! That's what I'm updating to as we speak, update incoming :)

File: buildengine/engine.go [hunk 2]
```diff
@@ -180,16 +190,32 @@ func (e *Engine) Dev(ctx context.Context, period time.Duration) error {
...
+		return true
+	})
+
+	schemaChanges := make(chan schemaChange, 128)
+	e.schemaChanges.Subscribe(schemaChanges)
+	defer e.schemaChanges.Unsubscribe(schemaChanges)
+
+	watchEvents := make(chan WatchEvent, 128)
 	watch := Watch(ctx, period, e.dirs...)
-	defer watch.Close()
```
[the remark this answers is not in the document]
Comment (alecthomas) [reply buildengine/engine.go:185]: This function owns the watch, so you want to `Close()` _as well as unsubscribing_.

File: buildengine/engine.go [hunk 3]
```diff
@@ -212,8 +238,55 @@ func (e *Engine) watchForModuleChanges(ctx context.Context, period time.Duration
 					logger.Errorf(err, "deploy %s failed", event.Module.Module)
 				}
 			}
+		case change := <-schemaChanges:
```
Comment (alecthomas) [inline buildengine/engine.go:241]: The design we discussed was that the `WatchEventModuleChanged` event would just have a hash added to it. Then you just use the normal watch system to detect if it's a schema change or a code change.

Comment (wesbillman) [reply buildengine/engine.go:241]: I started down that path, but since `Watch` was just watching for filesystem changes in the directories it seemed like it would need to do more than that to signal actual schema changes. I'd love to make that work though if that approach is better. The reason I did it this way is because I can make change to the code that would update the hash, but they aren't actual schema changes. For example if I add some new helper funcs or non-schema things, it would trigger us to rebuild the other modules. Whereas, really I don't think we need to rebuild other modules if the underlying schema does change.

I'm might be overthinking it though 🤔

Comment (alecthomas) [reply buildengine/engine.go:241]: Ah that makes sense. Because we wouldn't have the compiled schema in `Watch()`, only files?

File: buildengine/engine.go [hunk 4]
```diff
@@ -92,13 +100,15 @@ func (e *Engine) startSchemaSync(ctx context.Context) func(ctx context.Context,
 		switch msg.ChangeType {
 		case ftlv1.DeploymentChangeType_DEPLOYMENT_ADDED, ftlv1.DeploymentChangeType_DEPLOYMENT_CHANGED:
 			sch, err := schema.ModuleFromProto(msg.Schema)
-			if err == nil {
+			if err != nil {
 				return err
 			}
 			e.controllerSchema.Store(sch.Name, sch)
+			e.schemaChanges.Publish(schemaChange{ChangeType: msg.ChangeType, Module: sch})
```
Comment (alecthomas) [inline buildengine/engine.go:107]: I think you'll also want to Publish the schema to the topic when you build locally, for the situation where you're building offline? Or I guess we don't have a "dev" mode where we only build, so maybe not.

**Review by alecthomas — APPROVED** [review]

File: buildengine/engine.go (hunk 3 above)
Comment (wesbillman) [reply buildengine/engine.go:241]: That was my thought for now, but def open to ideas here.

File: buildengine/engine.go (hunk 4 above)
Comment (wesbillman) [reply buildengine/engine.go:107]: Yeah I think that's true. I think the dev mode is assuming hot reloading with real controller, etc.
