### PR TITLE
fix: do not replace deployment with itself

### LINKED ISSUE #2225: Pubsub seems to pause and then catch up for a minute while updating deployments
Seen by @jiyoontbd 

After some research:
It seems like deploying the same module twice can cause subscription and subscriber rows in the db to be removed.

### PR DESCRIPTION
**Pull request by matt2e**
fixes #2225

This was breaking pubsub because we would:
- upsert all subscribers and subscriptions to the new deployment (which is the same as the old deployment)
- then delete all subscribers and subscriptions from the old deployment (which is... bad)

We also had comments saying that the func would return that specific error in this case, but we were not returning it.

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

File: backend/controller/dal/dal.go [hunk 1]
```diff
@@ -752,6 +752,9 @@ func (d *DAL) ReplaceDeployment(ctx context.Context, newDeploymentKey model.Depl
 	var replacedDeploymentKey optional.Option[model.DeploymentKey]
 	oldDeployment, err := tx.GetExistingDeploymentForModule(ctx, newDeployment.ModuleName)
 	if err == nil {
+		if oldDeployment.Key.String() == newDeploymentKey.String() {
```
Comment (alecthomas) [inline backend/controller/dal/dal.go:755]: Are you sure this is a good idea? We used to do this and it resulted in a lot of errors being spewed out due to rebuilds occurring but the deployments being identical. Maybe things have changed though, this was a while ago.
